import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Soundboard Speaker System | Kawai Pianos',
  description:
    'Channeling sound energy onto a real wooden soundboard to produce natural, organic tone — the most authentic digital piano listening experience available.',
}

const steps = [
  {
    number: 1,
    title: 'Sound Generation',
    description:
      "Digital audio is generated by the piano's sound engine, reproducing the sampled tones of the Shigeru Kawai SK-EX concert grand.",
  },
  {
    number: 2,
    title: 'Transducer Technology',
    description:
      'High-performance transducers convert the electrical signal into mechanical vibration, channeling energy directly into the wooden soundboard.',
  },
  {
    number: 3,
    title: 'Natural Resonance',
    description:
      'The wooden soundboard and its ribs resonate naturally, producing warm, rich, expansive tone that fills the room with authentic acoustic character.',
  },
]

const featuredInstruments = [
  {
    name: 'CA99',
    description:
      "Kawai's flagship Concert Artist digital piano, featuring the Soundboard Speaker System alongside the Grand Feel III wooden-key action.",
  },
  {
    name: 'NV5S Hybrid',
    description:
      'A hybrid piano combining acoustic piano action components with digital sound generation, featuring the Soundboard Speaker System for unmatched authenticity.',
  },
  {
    name: 'AURES Series Uprights',
    description:
      'K-300 AURES and K-500 AURES bring the Soundboard Speaker System to traditional upright piano forms.',
  },
  {
    name: 'GX-2 AURES',
    description:
      'The flagship AURES grand piano, combining the acclaimed GX-2 acoustic grand with transducer technology for a complete silent/acoustic hybrid experience.',
  },
]

export default function SoundboardSpeakerSystemPage() {
  return (
    <div className="min-h-screen bg-kawai-pearl">
      {/* Hero */}
      <section className="bg-kawai-black text-white py-20">
        <div className="container mx-auto px-6">
          <div className="max-w-4xl mx-auto">
            <p className="text-kawai-red text-sm uppercase tracking-widest mb-3">Technology</p>
            <h1 className="text-4xl md:text-5xl font-[family-name:var(--font-brand-serif)] mb-4">
              Soundboard Speaker System
            </h1>
            <p className="text-lg text-white/70 max-w-2xl">
              Channeling sound energy onto a real wooden soundboard to produce natural, organic tone
              — the most authentic digital piano listening experience available.
            </p>
          </div>
        </div>
      </section>

      {/* The Soundboard Speaker System */}
      <section className="py-16 bg-kawai-pearl">
        <div className="container mx-auto px-6">
          <div className="max-w-4xl mx-auto">
            <h2 className="text-2xl md:text-3xl font-[family-name:var(--font-brand-serif)] text-kawai-black mb-6">
              The Soundboard Speaker System
            </h2>
            <p className="text-kawai-charcoal leading-relaxed">
              Found on Kawai&apos;s CA99 and NV5S Hybrid instruments, our unique Soundboard Speaker
              System embraces the resonant qualities of wood as it channels sound energy onto a real
              wooden soundboard to produce natural, organic tone. The long wooden ribs attached to
              the soundboard broaden the instrument&apos;s frequency range and volume, resulting in
              a remarkably authentic playing experience that faithfully reproduces the tonal
              ambiance of an acoustic piano.
            </p>
          </div>
        </div>
      </section>

      {/* How It Works */}
      <section className="py-16 bg-white">
        <div className="container mx-auto px-6">
          <div className="max-w-4xl mx-auto">
            <h2 className="text-2xl md:text-3xl font-[family-name:var(--font-brand-serif)] text-kawai-black mb-10">
              How It Works
            </h2>

            <div className="space-y-8">
              {steps.map((step) => (
                <div key={step.number} className="flex items-start gap-6">
                  <div className="flex-shrink-0 w-12 h-12 rounded-full bg-kawai-red text-white flex items-center justify-center font-bold text-lg">
                    {step.number}
                  </div>
                  <div>
                    <h3 className="text-lg font-semibold text-kawai-black mb-2">{step.title}</h3>
                    <p className="text-kawai-charcoal leading-relaxed">{step.description}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* AURES Series */}
      <section className="py-16 bg-kawai-pearl">
        <div className="container mx-auto px-6">
          <div className="max-w-4xl mx-auto">
            <h2 className="text-2xl md:text-3xl font-[family-name:var(--font-brand-serif)] text-kawai-black mb-6">
              AURES Series
            </h2>
            <p className="text-kawai-charcoal leading-relaxed mb-6">
              On Kawai&apos;s AURES series — which includes the K-300 AURES, K-500 AURES, GL-30
              AURES and the flagship GX-2 AURES — proprietary high-performance transducers are
              strategically mounted to the acoustic piano&apos;s solid spruce soundboard. By using
              the natural wood to amplify the digital sounds, warm, rich, expansive tone is
              produced.
            </p>
            <p className="text-kawai-charcoal leading-relaxed">
              This unique approach means AURES instruments function as both a traditional acoustic
              piano and a silent practice instrument with headphones, all while sharing the same
              soundboard for acoustic amplification.
            </p>
          </div>
        </div>
      </section>

      {/* Featured Instruments */}
      <section className="py-16 bg-white">
        <div className="container mx-auto px-6">
          <div className="max-w-4xl mx-auto">
            <h2 className="text-2xl md:text-3xl font-[family-name:var(--font-brand-serif)] text-kawai-black mb-8">
              Featured Instruments
            </h2>

            <div className="grid md:grid-cols-2 gap-6">
              {featuredInstruments.map((instrument) => (
                <div
                  key={instrument.name}
                  className="bg-kawai-pearl border border-kawai-neutral rounded-lg p-6"
                >
                  <h4 className="font-semibold text-kawai-black mb-3">{instrument.name}</h4>
                  <p className="text-kawai-charcoal text-sm leading-relaxed">
                    {instrument.description}
                  </p>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* Why Wood Matters */}
      <section className="py-16 bg-kawai-pearl">
        <div className="container mx-auto px-6">
          <div className="max-w-4xl mx-auto">
            <h2 className="text-2xl md:text-3xl font-[family-name:var(--font-brand-serif)] text-kawai-black mb-6">
              Why Wood Matters
            </h2>
            <p className="text-kawai-charcoal leading-relaxed">
              The choice to use a real wooden soundboard rather than synthetic materials is
              deliberate. Wood has been the primary medium for acoustic piano resonance for over 300
              years. Its complex cellular structure, natural density variation, and response to
              humidity give it a tonal character that no synthetic material has yet matched. By
              coupling digital sound generation to a real wood soundboard, Kawai&apos;s Soundboard
              Speaker System bridges the gap between digital and acoustic in a way that is
              genuinely unique in the industry.
            </p>
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-20 bg-kawai-black text-white">
        <div className="container mx-auto px-6 text-center">
          <h2 className="text-3xl md:text-4xl font-[family-name:var(--font-brand-serif)] mb-4">
            Experience It In Person
          </h2>
          <p className="text-white/70 text-lg mb-8 max-w-xl mx-auto">
            Discover the Soundboard Speaker System at an authorized Kawai dealer near you.
          </p>
          <Link
            href="/find-a-dealer"
            className="inline-block bg-kawai-red hover:bg-kawai-red-700 text-white px-8 py-4 rounded text-sm uppercase tracking-widest transition-colors"
          >
            Find a Dealer
          </Link>
        </div>
      </section>
    </div>
  )
}
