import { unstable_cache } from 'next/cache'
import { getPayloadClient } from '@/lib/payload/queries'
import type { Artist, Media } from '@/payload-types'
import { ArtistI2LRenderer } from './marketing/ArtistI2LRenderer'

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type VideoItem = {
  id: string
  title: string
  description: string | null
  youtubeUrl: string
  youtubeId: string
  date: string | null
  artistName: string | null
  artistSlug: string | null
  artistImageUrl: string | null
  isManual: boolean
  eyebrowText?: string | null
  ctaText?: string | null
  ctaUrl?: string | null
  ctaOpenInNewTab?: boolean | null
}

// Matches the shape generated by Payload for this block's fields.
// Will be superseded by the auto-generated MarketingArtistI2LBlock once
// `bun run build` regenerates payload-types.ts.
export type ArtistI2LBlockData = {
  id?: string | null
  blockType: 'marketing-artist-i2l'
  sectionLabel?: string | null
  heading?: string | null
  subheading?: string | null
  videos?: {
    title: string
    description?: string | null
    youtubeUrl: string
    eyebrowText?: string | null
    ctaText?: string | null
    ctaUrl?: string | null
    ctaOpenInNewTab?: boolean | null
    id?: string | null
  }[] | null
  showArtistVideos?: boolean | null
  maxArtistVideos?: number | null
  initialVisible?: number | null
  theme?: 'dark' | 'light' | null
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function extractYouTubeId(url: string): string | null {
  const match = url.match(/(?:youtube\.com\/(?:watch\?v=|embed\/)|youtu\.be\/)([^&?/\s]{11})/)
  return match?.[1] ?? null
}

function getArtistImage(artist: Artist): string | null {
  if (artist.heroImageUrl) return artist.heroImageUrl
  if (artist.image && typeof artist.image === 'object') {
    return (artist.image as Media).url ?? null
  }
  return artist.imageUrl ?? null
}

// ---------------------------------------------------------------------------
// Cached artist video fetch
// ---------------------------------------------------------------------------

type ArtistVideoResult = VideoItem[]

const getArtistYouTubeVideos = unstable_cache(
  async (maxVideos: number): Promise<ArtistVideoResult> => {
    const payload = await getPayloadClient()
    const { docs } = await payload.find({
      collection: 'artists',
      where: { isActive: { equals: true } },
      depth: 1,
      limit: 500,
      select: {
        name: true,
        slug: true,
        image: true,
        imageUrl: true,
        heroImageUrl: true,
        recentWork: true,
      },
    })

    const items: VideoItem[] = []

    for (const artist of docs as Artist[]) {
      if (!artist.recentWork?.length) continue
      const artistImageUrl = getArtistImage(artist)

      for (const work of artist.recentWork) {
        if (work.platform !== 'youtube' || !work.link) continue
        const youtubeId = extractYouTubeId(work.link)
        if (!youtubeId) continue

        items.push({
          id: `artist-${artist.id}-${work.id ?? youtubeId}`,
          title: work.title,
          description: work.description ?? null,
          youtubeUrl: work.link,
          youtubeId,
          date: work.date ?? null,
          artistName: artist.name,
          artistSlug: artist.slug ?? null,
          artistImageUrl,
          isManual: false,
        })
      }
    }

    // Sort by date descending — undated items at the end
    items.sort((a, b) => {
      if (!a.date && !b.date) return 0
      if (!a.date) return 1
      if (!b.date) return -1
      return new Date(b.date).getTime() - new Date(a.date).getTime()
    })

    return items.slice(0, maxVideos)
  },
  ['artist-i2l-videos'],
  { tags: ['artists'], revalidate: 3600 },
)

// ---------------------------------------------------------------------------
// Server component
// ---------------------------------------------------------------------------

export async function ArtistI2LBlock(props: ArtistI2LBlockData) {
  const { videos: manualVideos, showArtistVideos, maxArtistVideos, initialVisible, ...rest } = props

  // Build manual video items
  const manualItems: VideoItem[] = []
  for (const v of manualVideos ?? []) {
    if (!v.youtubeUrl) continue
    const youtubeId = extractYouTubeId(v.youtubeUrl)
    if (!youtubeId) continue
    manualItems.push({
      id: `manual-${youtubeId}`,
      title: v.title,
      description: v.description ?? null,
      youtubeUrl: v.youtubeUrl,
      youtubeId,
      date: null,
      artistName: null,
      artistSlug: null,
      artistImageUrl: null,
      isManual: true,
      eyebrowText: v.eyebrowText ?? null,
      ctaText: v.ctaText ?? null,
      ctaUrl: v.ctaUrl ?? null,
      ctaOpenInNewTab: v.ctaOpenInNewTab ?? null,
    })
  }

  const artistItems = showArtistVideos !== false
    ? await getArtistYouTubeVideos(maxArtistVideos ?? 30)
    : []

  const allVideos: VideoItem[] = [...manualItems, ...artistItems]

  if (allVideos.length === 0) return null

  return (
    <ArtistI2LRenderer
      {...rest}
      resolvedVideos={allVideos}
      initialVisible={initialVisible ?? 3}
    />
  )
}
