// Content blocks (for blog articles)
export { Text } from './content/Text'
export { Image } from './content/Image'
export { Video } from './content/Video'
export { Code } from './content/Code'
export { Banner } from './content/Banner'
export { RichTextContent } from './content/RichTextContent'
export { ContentCta } from './content/ContentCta'

// Layout blocks (structural)
export { Columns } from './layout/Columns'
export { Spacer } from './layout/Spacer'
export { Divider } from './layout/Divider'
export { HeroCarousel } from './layout/HeroCarousel'
export { VideoBackground } from './layout/VideoBackground'
export { BrandIntro } from './layout/BrandIntro'
export { BottomLeftPopup } from './layout/BottomLeftPopup'
export { SideNavigation } from './layout/SideNavigation'
export { CalendlyEmbed } from './layout/CalendlyEmbed'
export { BookingModal } from './layout/BookingModal'

// Marketing blocks (conversion-focused)
export { Hero } from './marketing/Hero'
export { GrandHero } from './marketing/GrandHero'
export { CallToAction } from './marketing/CallToAction'
export { Testimonials } from './marketing/Testimonials'
export { InstrumentalToLife } from './marketing/InstrumentalToLife'
export { TechnicalShowcase } from './marketing/TechnicalShowcase'
export { FindADealer } from './marketing/FindADealer'
export { DealerFinder } from './marketing/DealerFinder'
export { ThreeDViewer } from './marketing/ThreeDViewer'
export { ArtistCarousel } from './marketing/ArtistCarousel'
export { ArtistI2L } from './marketing/ArtistI2L'
export { HomePageHero } from './marketing/HomePageHero'
export { Showroom } from './marketing/Showroom'
export { PianoCollection } from './marketing/PianoCollection'
export { PianoGallery } from './marketing/PianoGallery'
export { NewsCarousel } from './marketing/NewsCarousel'
export { ContactForm } from './marketing/ContactForm'
export { StorefrontLocations } from './marketing/StorefrontLocations'
export { FeaturedModels } from './marketing/FeaturedModels'
export { FeaturedCollections } from './marketing/FeaturedCollections'
export { RebateTable } from './marketing/RebateTable'
export { ArtistHero } from './marketing/ArtistHero'
export { PianosBrowser } from './marketing/PianosBrowser'
export { ArtistsGrid } from './marketing/ArtistsGrid'
export { BlogGrid } from './marketing/BlogGrid'
export { BlogLatest } from './marketing/BlogLatest'
export { NewsletterPopup } from './marketing/NewsletterPopup'

// Events blocks (event-specific content)
export { UniversityHero } from './events/UniversityHero'
export { EventOverview } from './events/EventOverview'

// University blocks (university event microsites)
export { UniversityAbout } from './university/UniversityAbout'
export { UniversityBooking } from './university/UniversityBooking'
export { UniversityCountdown } from './university/UniversityCountdown'
export { UniversityEventDetails } from './university/UniversityEventDetails'
export { UniversityEventHero } from './university/UniversityEventHero'
export { UniversityFaq } from './university/UniversityFaq'
export { UniversityLocation } from './university/UniversityLocation'
export { UniversityPianoShowcase } from './university/UniversityPianoShowcase'
export { UniversitySocialProof } from './university/UniversitySocialProof'
export { UniversityValueProps } from './university/UniversityValueProps'

// Product blocks (product pages)
export { ProductShowcase } from './product/ProductShowcase'
export { ProductHero } from './product/ProductHero'
export { ProductDescription } from './product/ProductDescription'
export { ImageGallery } from './product/ImageGallery'
export { FeaturesList } from './product/FeaturesList'
export { Specifications } from './product/Specifications'
export { TechnicalSpecifications } from './product/TechnicalSpecifications'
export { CollectionShowcase } from './product/CollectionShowcase'
export { FloatingAddToCart } from './product/FloatingAddToCart'
export { ProductFeatureSlides } from './product/ProductFeatureSlides'
export { ProductHeroCarousel } from './product/ProductHeroCarousel'
export { RelatedProducts } from './product/RelatedProducts'
export { SoundCloudEmbed } from './product/SoundCloudEmbed'
export { ProductFaqBlock } from './product/ProductFaq'
export { PianoPages } from './product/PianoPages'
export { ProductAccessories } from './product/ProductAccessories'
export { ProductReference } from './product/ProductReference'

// Legacy blocks (keep for backward compatibility - TODO: migrate away from these)
export { Hello } from './Hello'
export { TextContent } from './TextContent'
export { Archive } from './Archive'
export { Content } from './Content'
export { MediaBlock } from './MediaBlock'
export { Cta } from './Cta'