#!/usr/bin/env bun
/**
 * Generates src/lib/data/dealers-seed-data.ts from an Excel (.xlsx) source file.
 *
 * Usage:
 *   bun scripts/generate-dealer-seed.ts [path/to/file.xlsx] > src/lib/data/dealers-seed-data.ts
 *
 * Reads the first sheet ("Updated Dealer List") which has columns matching
 * the DealerSeedEntry type. Boolean values may come as "True"/"False" strings
 * or actual booleans depending on the Excel cell type.
 */

import * as XLSX from 'xlsx'

const XLSX_PATH =
  process.argv[2] ??
  '/Users/chancenoonan/Library/Application Support/Claude/local-agent-mode-sessions/4e22694c-2efd-41dc-8fdd-5bbdb15c1efb/82058319-0efa-4063-9b01-8e98ed98ef9d/local_43124ee5-0cdc-4076-a0f9-6eda1642f3dc/outputs/Dealer_List_Update.xlsx'

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------
function bool(val: unknown): boolean {
  if (typeof val === 'boolean') return val
  if (typeof val === 'string') return val.trim().toUpperCase() === 'TRUE'
  if (typeof val === 'number') return val !== 0
  return false
}

function str(val: unknown): string | undefined {
  if (val === null || val === undefined) return undefined
  const s = String(val).trim()
  return s.length > 0 ? s : undefined
}

// Take only the first email if comma-separated; discard if it looks like a URL
function parseEmail(val: unknown): string | undefined {
  const raw = str(val)
  if (!raw) return undefined
  const first = raw.split(',')[0]?.trim() ?? ''
  if (!first || first.startsWith('http') || !first.includes('@')) return undefined
  return first
}

function num(val: unknown): number | undefined {
  if (val === null || val === undefined || val === '') return undefined
  const n = typeof val === 'number' ? val : parseFloat(String(val))
  return isNaN(n) ? undefined : n
}

function escapeStr(val: string): string {
  return val.replace(/\\/g, '\\\\').replace(/'/g, "\\'")
}

function renderOptNum(val: number | undefined): string {
  return val !== undefined ? String(val) : 'undefined'
}

// ---------------------------------------------------------------------------
// Read Excel
// ---------------------------------------------------------------------------
const wb = XLSX.readFile(XLSX_PATH)
const sheetName = wb.SheetNames[0]!
const ws = wb.Sheets[sheetName]!

// header: 1 → array of arrays; row[0] = headers
const rawRows = XLSX.utils.sheet_to_json<unknown[]>(ws, { header: 1 })
const headers = rawRows[0] as string[]
const dataRows = rawRows.slice(1).filter((r) => (r as unknown[]).some((c) => c !== null && c !== undefined && c !== ''))

// Build column index map
const colIdx: Record<string, number> = {}
for (const h of headers) {
  colIdx[h] = headers.indexOf(h)
}

function col(row: unknown[], name: string): unknown {
  const idx = colIdx[name]
  if (idx === undefined) return undefined
  return row[idx]
}

// ---------------------------------------------------------------------------
// Map rows to entries
// ---------------------------------------------------------------------------
const entries = dataRows.map((row) => ({
  dealerName:              str(col(row, 'dealerName')) ?? '',
  slug:                    str(col(row, 'slug')) ?? '',
  isActive:                bool(col(row, 'isActive')),
  isFeatured:              bool(col(row, 'isFeatured')),
  dealerIdentification:    str(col(row, 'dealerIdentification')),
  phone:                   str(col(row, 'phone')),
  email:                   parseEmail(col(row, 'email')),
  website:                 str(col(row, 'website')),
  fax:                     str(col(row, 'fax')),
  street:                  str(col(row, 'street')),
  city:                    str(col(row, 'city')),
  state:                   str(col(row, 'state')),
  zipCode:                 str(col(row, 'zipCode')),
  country:                 str(col(row, 'country')),
  latitude:                num(col(row, 'latitude')),
  longitude:               num(col(row, 'longitude')),
  shigeruKawaiDealer:      bool(col(row, 'shigeruKawaiDealer')),
  acousticPianoDealer:     bool(col(row, 'acousticPianoDealer')),
  professionalProductDealer: bool(col(row, 'professionalProductDealer')),
  description:             str(col(row, 'description')),
  metaTitle:               str(col(row, 'metaTitle')),
  metaDescription:         str(col(row, 'metaDescription')),
}))

// ---------------------------------------------------------------------------
// Render TypeScript output
// ---------------------------------------------------------------------------
const lines: string[] = []

lines.push(`// AUTO-GENERATED by scripts/generate-dealer-seed.ts`)
lines.push(`// Source: Dealer_List_Update.xlsx — sheet: "${sheetName}" (${entries.length} entries)`)
lines.push(`// DO NOT EDIT MANUALLY — re-run the generation script instead.`)
lines.push(``)
lines.push(`export type DealerSeedEntry = {`)
lines.push(`  dealerName: string`)
lines.push(`  slug: string`)
lines.push(`  isActive: boolean`)
lines.push(`  isFeatured: boolean`)
lines.push(`  dealerIdentification?: string`)
lines.push(`  phone?: string`)
lines.push(`  fax?: string`)
lines.push(`  email?: string`)
lines.push(`  website?: string`)
lines.push(`  street?: string`)
lines.push(`  city?: string`)
lines.push(`  state?: string`)
lines.push(`  zipCode?: string`)
lines.push(`  country?: string`)
lines.push(`  latitude?: number`)
lines.push(`  longitude?: number`)
lines.push(`  shigeruKawaiDealer: boolean`)
lines.push(`  acousticPianoDealer: boolean`)
lines.push(`  digitalPianoDealer: boolean`)
lines.push(`  professionalProductDealer: boolean`)
lines.push(`  description?: string`)
lines.push(`  metaTitle?: string`)
lines.push(`  metaDescription?: string`)
lines.push(`}`)
lines.push(``)
lines.push(`export const DEALER_SEED_DATA: DealerSeedEntry[] = [`)

for (const e of entries) {
  lines.push(`  {`)
  lines.push(`    dealerName: '${escapeStr(e.dealerName)}',`)
  lines.push(`    slug: '${escapeStr(e.slug)}',`)
  lines.push(`    isActive: ${e.isActive},`)
  lines.push(`    isFeatured: ${e.isFeatured},`)
  if (e.dealerIdentification !== undefined) lines.push(`    dealerIdentification: '${escapeStr(e.dealerIdentification)}',`)
  if (e.phone !== undefined)    lines.push(`    phone: '${escapeStr(e.phone)}',`)
  if (e.fax !== undefined)      lines.push(`    fax: '${escapeStr(e.fax)}',`)
  if (e.email !== undefined)    lines.push(`    email: '${escapeStr(e.email)}',`)
  if (e.website !== undefined)  lines.push(`    website: '${escapeStr(e.website)}',`)
  if (e.street !== undefined)   lines.push(`    street: '${escapeStr(e.street)}',`)
  if (e.city !== undefined)     lines.push(`    city: '${escapeStr(e.city)}',`)
  if (e.state !== undefined)    lines.push(`    state: '${escapeStr(e.state)}',`)
  if (e.zipCode !== undefined)  lines.push(`    zipCode: '${escapeStr(e.zipCode)}',`)
  if (e.country !== undefined)  lines.push(`    country: '${escapeStr(e.country)}',`)
  if (e.latitude !== undefined)  lines.push(`    latitude: ${renderOptNum(e.latitude)},`)
  if (e.longitude !== undefined) lines.push(`    longitude: ${renderOptNum(e.longitude)},`)
  lines.push(`    shigeruKawaiDealer: ${e.shigeruKawaiDealer},`)
  lines.push(`    acousticPianoDealer: ${e.acousticPianoDealer},`)
  lines.push(`    digitalPianoDealer: false,`)
  lines.push(`    professionalProductDealer: ${e.professionalProductDealer},`)
  if (e.description !== undefined)    lines.push(`    description: '${escapeStr(e.description)}',`)
  if (e.metaTitle !== undefined)      lines.push(`    metaTitle: '${escapeStr(e.metaTitle)}',`)
  if (e.metaDescription !== undefined) lines.push(`    metaDescription: '${escapeStr(e.metaDescription)}',`)
  lines.push(`  },`)
}

lines.push(`]`)
lines.push(``)

process.stdout.write(lines.join('\n'))
process.stderr.write(`\nGenerated ${entries.length} dealer entries from sheet "${sheetName}".\n`)
