/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {
    productShowcase: ProductShowcaseBlock;
    productHero: ProductHeroBlock;
    hero: HeroBlock;
    textContent: TextContentBlock;
    imageGallery: ImageGalleryBlock;
    featuresList: FeaturesListBlock;
    specifications: SpecificationsBlock;
    callToAction: CallToActionBlock;
    testimonials: TestimonialsBlock;
    hello: HelloBlock;
  };
  collections: {
    users: User;
    media: Media;
    'home-page': HomePage;
    'pianos-page': PianosPage;
    storefronts: Storefront;
    'concert-artist-page': ConcertArtistPage;
    products: Product;
    productlines: Productline;
    'constant-contact-settings': ConstantContactSetting;
    'constant-contact-custom-fields': ConstantContactCustomField;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    productlines: {
      products: 'products';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'pianos-page': PianosPageSelect<false> | PianosPageSelect<true>;
    storefronts: StorefrontsSelect<false> | StorefrontsSelect<true>;
    'concert-artist-page': ConcertArtistPageSelect<false> | ConcertArtistPageSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    productlines: ProductlinesSelect<false> | ProductlinesSelect<true>;
    'constant-contact-settings': ConstantContactSettingsSelect<false> | ConstantContactSettingsSelect<true>;
    'constant-contact-custom-fields': ConstantContactCustomFieldsSelect<false> | ConstantContactCustomFieldsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductShowcaseBlock".
 */
export interface ProductShowcaseBlock {
  /**
   * Choose data source for product information
   */
  dataSource?: ('manual' | 'pianomodel' | 'hybrid') | null;
  /**
   * Select piano model to automatically populate product information
   */
  pianoModel?: (string | null) | Product;
  /**
   * Product showcase configuration
   */
  product: {
    /**
     * Main product image (leave empty to use Piano Model image)
     */
    image?: (string | null) | Media;
    /**
     * Product title/name (leave empty to use Piano Model name)
     */
    title?: string | null;
    /**
     * Product description (leave empty to use Piano Model description)
     */
    description?: string | null;
    /**
     * Product pricing information (overrides Piano Model pricing when provided)
     */
    price?: {
      /**
       * Price currency (leave empty to use Piano Model currency)
       */
      currency?: ('USD' | 'EUR' | 'GBP' | 'CAD') | null;
      /**
       * Price amount (leave empty to use Piano Model pricing)
       */
      amount?: number | null;
      /**
       * Sale price (leave empty to use Piano Model sale price)
       */
      saleAmount?: number | null;
      /**
       * Custom price text (leave empty to use Piano Model price text)
       */
      priceText?: string | null;
    };
    /**
     * Available finish options (overrides Piano Model finishes when provided)
     */
    finishes?:
      | {
          /**
           * Finish name (e.g., "Ebony Polish", "White Satin")
           */
          name: string;
          /**
           * Finish sample image (optional)
           */
          image?: (string | null) | Media;
          /**
           * Price difference for this finish (+ or -)
           */
          priceModifier?: number | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Buy button configuration
     */
    buyButton: {
      /**
       * Button text
       */
      text: string;
      /**
       * Button link/URL (leave empty to disable button)
       */
      link?: string | null;
      /**
       * Button style
       */
      style?: ('primary' | 'secondary' | 'outline') | null;
      /**
       * Open link in new tab
       */
      openInNewTab?: boolean | null;
    };
    /**
     * Optional badge text (e.g., "Best Seller", "New", "Limited Edition")
     */
    badge?: string | null;
    /**
     * Is this product currently in stock?
     */
    inStock?: boolean | null;
  };
  /**
   * Layout and display options
   */
  layout?: {
    /**
     * Position of product image relative to content
     */
    imagePosition?: ('left' | 'right' | 'top' | 'bottom') | null;
    /**
     * Show available finishes in this block
     */
    showFinishes?: boolean | null;
    /**
     * Show pricing information in this block
     */
    showPrice?: boolean | null;
    /**
     * Use compact layout (smaller spacing, condensed content)
     */
    compact?: boolean | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'productShowcase';
}
/**
 * Unified product management - pianos, accessories, and other products with dynamic page building
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  /**
   * Product type determines available features and data structure
   */
  type: 'piano' | 'accessory' | 'software' | 'other';
  /**
   * Product name/title
   */
  name: string;
  /**
   * URL-friendly version of product name
   */
  slug: string;
  /**
   * Product category for organization
   */
  category: 'digital' | 'grand' | 'hybrid' | 'upright' | 'accessories' | 'software';
  /**
   * Product availability status
   */
  status?: ('active' | 'draft' | 'discontinued' | 'coming-soon' | 'limited-edition') | null;
  /**
   * Primary product image (optional)
   */
  mainImage?: (string | null) | Media;
  /**
   * Direct image URL (used during CSV migration or when media upload is not available)
   */
  imageUrl?: string | null;
  /**
   * Product description for listings and meta
   */
  description: string;
  /**
   * Short description for compact displays and listings
   */
  shortDescription?: string | null;
  /**
   * Optional URL for the "Learn More" button (e.g., /products/piano-name or https://example.com)
   */
  learnMore?: string | null;
  /**
   * Product pricing information
   */
  price?: {
    currency?: ('USD' | 'EUR' | 'GBP' | 'CAD') | null;
    /**
     * MSRP (Manufacturer Suggested Retail Price)
     */
    msrp?: number | null;
    /**
     * Sale price if different from MSRP
     */
    salePrice?: number | null;
    /**
     * Price range text (e.g., "$15,000 - $20,000")
     */
    priceRange?: string | null;
    /**
     * Custom price text (e.g., "Starting from", "Contact for pricing")
     */
    priceText?: string | null;
    /**
     * Check if pricing is by contact only
     */
    contactForPricing?: boolean | null;
    /**
     * Display price on product pages
     */
    showPrice?: boolean | null;
  };
  /**
   * Available finish options
   */
  finishes?:
    | {
        /**
         * Finish name (e.g., "Ebony Polish", "White Satin")
         */
        name: string;
        /**
         * Finish sample image
         */
        image?: (string | null) | Media;
        /**
         * Price difference for this finish (+ or -)
         */
        priceModifier?: number | null;
        /**
         * Is this finish currently available?
         */
        available?: boolean | null;
        /**
         * Optional finish description
         */
        description?: string | null;
        /**
         * Direct image URL for this finish (used during CSV migration)
         */
        imageUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * The product line/series this product belongs to
   */
  productline?: (string | null) | Productline;
  /**
   * Product series/collection (auto-populated for pianos)
   */
  series?: string | null;
  /**
   * Product model number/identifier
   */
  model?: string | null;
  /**
   * Customer rating (0-5 stars)
   */
  rating?: number | null;
  /**
   * Number of customer reviews
   */
  reviews?: number | null;
  /**
   * Optional badge text (e.g., "Best Seller", "Featured")
   */
  badge?: string | null;
  /**
   * Optional highlight text for special promotions
   */
  highlight?: string | null;
  /**
   * Product brand/manufacturer
   */
  brand?: string | null;
  /**
   * Main selling points and key features
   */
  keyFeatures?:
    | {
        feature: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Complete product specifications and technical details
   */
  specifications?: {
    /**
     * Number of keys
     */
    keys?: number | null;
    /**
     * Number of pedals
     */
    pedals?: number | null;
    /**
     * Number of voices/sounds
     */
    voices?: number | null;
    /**
     * Maximum polyphony
     */
    polyphony?: number | null;
    /**
     * Action technology (e.g., "Grand Feel III")
     */
    actionType?: string | null;
    /**
     * Sound engine technology
     */
    soundEngine?: string | null;
    dimensions?: {
      /**
       * Width (e.g., "145cm", "57 inches")
       */
      width?: string | null;
      /**
       * Depth (e.g., "46cm", "18 inches")
       */
      depth?: string | null;
      /**
       * Height (e.g., "88cm", "35 inches")
       */
      height?: string | null;
    };
    /**
     * Product weight (e.g., "68kg", "150 lbs")
     */
    weight?: string | null;
    /**
     * Stock Keeping Unit (SKU)
     */
    sku?: string | null;
    /**
     * Warranty information
     */
    warranty?: string | null;
    /**
     * Country of manufacture
     */
    origin?: string | null;
  };
  /**
   * Buy button configuration
   */
  buyButton: {
    /**
     * Buy button text
     */
    text: string;
    /**
     * Buy button link (leave empty to use default contact form)
     */
    link?: string | null;
    style?: ('primary' | 'secondary' | 'outline') | null;
    /**
     * Show buy button on product pages
     */
    showButton?: boolean | null;
  };
  /**
   * Mark this product as discontinued
   */
  discontinued?: boolean | null;
  /**
   * 3D model viewer configuration
   */
  viewer3D?: {
    /**
     * Enable 3D model viewer for this product
     */
    enabled?: boolean | null;
    /**
     * Full URL to the 3D viewer (e.g., https://www.kawai-global.com/modelviewer/index.php)
     */
    viewerUrl?: string | null;
    /**
     * URL parameters for the model (e.g., ?model=gl-10&color=ebony)
     */
    modelParams?: string | null;
    /**
     * Automatically open 3D viewer when ?mode=3d URL parameter is present
     */
    autoOpen?: boolean | null;
    /**
     * Custom text for the 3D viewer button
     */
    buttonText?: string | null;
  };
  /**
   * Build your product page content using flexible blocks
   */
  pageContent?:
    | (
        | ProductShowcaseBlock
        | ProductHeroBlock
        | HeroBlock
        | TextContentBlock
        | ImageGalleryBlock
        | FeaturesListBlock
        | SpecificationsBlock
        | CallToActionBlock
        | TestimonialsBlock
      )[]
    | null;
  /**
   * SEO and social media optimization
   */
  seo?: {
    /**
     * Custom meta title (defaults to product title)
     */
    metaTitle?: string | null;
    /**
     * Meta description for search engines (max 160 characters)
     */
    metaDescription?: string | null;
    /**
     * SEO keywords (comma-separated)
     */
    keywords?: string | null;
    /**
     * Open Graph image for social sharing (defaults to main image)
     */
    ogImage?: (string | null) | Media;
  };
  /**
   * Product visibility and display settings
   */
  visibility?: {
    /**
     * Feature this product prominently
     */
    featured?: boolean | null;
    /**
     * Show in product catalog/listings
     */
    showInCatalog?: boolean | null;
    /**
     * Allow customer reviews for this product
     */
    allowReviews?: boolean | null;
    /**
     * Sort order (lower numbers appear first)
     */
    sortOrder?: number | null;
  };
  /**
   * Inventory management settings
   */
  inventory?: {
    /**
     * Track inventory for this product
     */
    trackStock?: boolean | null;
    /**
     * Current stock quantity
     */
    stockQuantity?: number | null;
    /**
     * Alert when stock falls below this number
     */
    lowStockThreshold?: number | null;
    /**
     * Product is currently in stock
     */
    inStock?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Media library for images, videos, and documents
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Alternative text for accessibility and SEO. Describe what the image shows.
   */
  alt: string;
  /**
   * Optional caption displayed with the image
   */
  caption?: string | null;
  /**
   * Detailed description for administrative purposes
   */
  description?: string | null;
  /**
   * Type of media for better organization
   */
  mediaType?: ('image' | 'video' | 'audio' | 'document') | null;
  /**
   * Where this media is intended to be used
   */
  usage?:
    | ('hero' | 'product' | 'category' | 'carousel' | 'background' | 'thumbnail' | 'technical' | 'marketing')[]
    | null;
  /**
   * Video-specific metadata
   */
  videoMeta?: {
    /**
     * Video duration in seconds
     */
    duration?: number | null;
    /**
     * Custom thumbnail for the video
     */
    thumbnail?: (string | null) | Media;
    /**
     * Should this video autoplay (use sparingly)
     */
    autoplay?: boolean | null;
    /**
     * Start video muted (recommended for autoplay)
     */
    muted?: boolean | null;
  };
  /**
   * Responsive image variants (generated automatically when uploaded)
   */
  variants?: {
    /**
     * Optimized for mobile devices (480px width)
     */
    mobile?: (string | null) | Media;
    /**
     * Optimized for tablets (768px width)
     */
    tablet?: (string | null) | Media;
    /**
     * Optimized for desktop (1200px width)
     */
    desktop?: (string | null) | Media;
    /**
     * Optimized for large screens (1920px width)
     */
    largeDesktop?: (string | null) | Media;
  };
  /**
   * SEO and technical metadata
   */
  seoMeta?: {
    /**
     * Keywords this image relates to (comma-separated)
     */
    focusKeywords?: string | null;
    /**
     * Photo credit information
     */
    photographerCredit?: string | null;
    /**
     * Copyright or licensing information
     */
    copyrightInfo?: string | null;
    /**
     * Original source or URL if external
     */
    originalSource?: string | null;
  };
  /**
   * Mark as featured media for easy access
   */
  featured?: boolean | null;
  /**
   * Tags for organization and search (e.g., "grand-piano", "black-finish")
   */
  tags?: string[] | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    desktop?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Piano product lines and series management
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productlines".
 */
export interface Productline {
  id: string;
  /**
   * Series name (e.g., "CA Series", "Shigeru Kawai SK Series")
   */
  name: string;
  /**
   * URL-friendly version of name
   */
  slug: string;
  /**
   * Piano category for organizing series
   */
  category: 'digital' | 'grand' | 'hybrid' | 'upright';
  /**
   * Main series description for the browser
   */
  description: string;
  /**
   * Optional highlighted callout text
   */
  highlight?: string | null;
  /**
   * Main series image displayed in the browser (can be added after seeding)
   */
  image?: (string | null) | Media;
  /**
   * Additional slides for the clean series browser carousel
   */
  slides?:
    | {
        /**
         * Title for this slide
         */
        title: string;
        /**
         * Slide image (can be added after seeding)
         */
        image?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Products in this series (automatically populated)
   */
  products?: {
    docs?: (string | Product)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Feature this series prominently
   */
  featured?: boolean | null;
  /**
   * Display order (lower numbers first)
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductHeroBlock".
 */
export interface ProductHeroBlock {
  /**
   * Layout and display options for the product hero
   */
  layout?: {
    /**
     * Position of product image relative to content
     */
    imagePosition?: ('left' | 'right') | null;
    /**
     * Background color for the hero section
     */
    backgroundColor?: ('pearl' | 'white' | 'black') | null;
    /**
     * Show available finishes section
     */
    showFinishes?: boolean | null;
    /**
     * Show pricing information
     */
    showPrice?: boolean | null;
    /**
     * Show buy/contact button
     */
    showBuyButton?: boolean | null;
  };
  /**
   * Optional overrides for product data (leave empty to use product document data)
   */
  overrides?: {
    /**
     * Override the product name with a custom title (optional)
     */
    customTitle?: string | null;
    /**
     * Override the product description with custom text (optional)
     */
    customDescription?: string | null;
    /**
     * Override the main product image (optional)
     */
    customImage?: (string | null) | Media;
    /**
     * Optional badge text (e.g., "Best Seller", "New", "Limited Edition")
     */
    badge?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'productHero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  /**
   * Choose data source for hero content
   */
  dataSource?: ('manual' | 'pianomodel' | 'hybrid') | null;
  /**
   * Select piano model to automatically populate hero content
   */
  pianoModel?: (string | null) | Product;
  /**
   * Hero content and call-to-action buttons
   */
  content?: {
    /**
     * Main hero title/headline (leave empty to use Piano Model name)
     */
    title?: string | null;
    /**
     * Optional subtitle or tagline (leave empty to use Piano Model short description)
     */
    subtitle?: string | null;
    /**
     * Hero description text (leave empty to use Piano Model description)
     */
    description?: string | null;
    /**
     * Primary call-to-action button
     */
    primaryCta?: {
      /**
       * Primary button text (leave empty to hide button)
       */
      text?: string | null;
      /**
       * Primary button link/URL
       */
      link?: string | null;
      style?: ('primary' | 'secondary' | 'outline') | null;
      openInNewTab?: boolean | null;
    };
    /**
     * Secondary call-to-action button (optional)
     */
    secondaryCta?: {
      /**
       * Secondary button text (leave empty to hide button)
       */
      text?: string | null;
      /**
       * Secondary button link/URL
       */
      link?: string | null;
      style?: ('primary' | 'secondary' | 'outline') | null;
      openInNewTab?: boolean | null;
    };
  };
  /**
   * Background media and overlay settings
   */
  media?: {
    /**
     * Type of background media
     */
    type?: ('image' | 'video' | 'none') | null;
    /**
     * Background image (leave empty to use Piano Model main image)
     */
    backgroundImage?: (string | null) | Media;
    /**
     * Background video
     */
    backgroundVideo?: (string | null) | Media;
    /**
     * Background overlay settings
     */
    overlay?: {
      /**
       * Add overlay to improve text readability
       */
      enable?: boolean | null;
      color?: ('dark' | 'light' | 'brand') | null;
      /**
       * Overlay opacity (0 = transparent, 1 = opaque)
       */
      opacity?: number | null;
    };
  };
  /**
   * Layout and positioning options
   */
  layout?: {
    /**
     * Hero section height
     */
    height?: ('small' | 'medium' | 'large' | 'fullscreen') | null;
    /**
     * Text content alignment
     */
    contentAlignment?: ('left' | 'center' | 'right') | null;
    /**
     * Vertical content alignment
     */
    verticalAlignment?: ('top' | 'center' | 'bottom') | null;
    /**
     * Maximum width of content area
     */
    maxWidth?: ('small' | 'medium' | 'large' | 'full') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextContentBlock".
 */
export interface TextContentBlock {
  /**
   * Rich text content with full formatting capabilities
   */
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Layout and styling options
   */
  layout?: {
    /**
     * Maximum width of text content
     */
    maxWidth?: ('small' | 'medium' | 'large' | 'full') | null;
    /**
     * Text alignment
     */
    textAlign?: ('left' | 'center' | 'right' | 'justify') | null;
    /**
     * Background color for the content area
     */
    backgroundColor?: ('none' | 'light-gray' | 'dark-gray' | 'brand' | 'accent') | null;
    /**
     * Padding around the content
     */
    padding?: ('none' | 'small' | 'medium' | 'large') | null;
    /**
     * Number of columns for text layout
     */
    columns?: ('one' | 'two' | 'three') | null;
  };
  /**
   * Enable drop cap (large first letter) for the first paragraph
   */
  enableDropCap?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'textContent';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageGalleryBlock".
 */
export interface ImageGalleryBlock {
  /**
   * Choose data source for gallery images
   */
  dataSource?: ('manual' | 'pianomodel' | 'hybrid') | null;
  /**
   * Select piano model to automatically populate gallery from model images
   */
  pianoModel?: (string | null) | Product;
  /**
   * Optional gallery title
   */
  title?: string | null;
  /**
   * Optional gallery description
   */
  description?: string | null;
  /**
   * Images to display in the gallery (additional images when using Piano Model data source)
   */
  images?:
    | {
        /**
         * Gallery image
         */
        image: string | Media;
        /**
         * Image caption (optional)
         */
        caption?: string | null;
        /**
         * Alt text for accessibility (optional, will use image alt if not provided)
         */
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Gallery layout and display options
   */
  layout?: {
    /**
     * Gallery display style
     */
    style?: ('grid' | 'masonry' | 'carousel' | 'lightbox') | null;
    /**
     * Number of columns for grid layouts
     */
    columns?: ('two' | 'three' | 'four' | 'five') | null;
    /**
     * Spacing between images
     */
    spacing?: ('none' | 'small' | 'medium' | 'large') | null;
    /**
     * Aspect ratio for images in grid layouts
     */
    aspectRatio?: ('original' | 'square' | 'landscape' | 'portrait') | null;
  };
  /**
   * Carousel-specific settings
   */
  carouselSettings?: {
    /**
     * Auto-advance slides
     */
    autoplay?: boolean | null;
    /**
     * Autoplay speed in milliseconds
     */
    autoplaySpeed?: number | null;
    /**
     * Show navigation dots
     */
    showDots?: boolean | null;
    /**
     * Show navigation arrows
     */
    showArrows?: boolean | null;
    /**
     * Number of slides to show at once
     */
    slidesToShow?: ('one' | 'two' | 'three' | 'four') | null;
    /**
     * Enable infinite loop
     */
    infinite?: boolean | null;
  };
  /**
   * Enable image zoom on hover/click
   */
  enableZoom?: boolean | null;
  /**
   * Display image captions
   */
  showCaptions?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'imageGallery';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturesListBlock".
 */
export interface FeaturesListBlock {
  /**
   * Choose data source for features list
   */
  dataSource?: ('manual' | 'pianomodel' | 'hybrid') | null;
  /**
   * Select piano model to automatically populate key features
   */
  pianoModel?: (string | null) | Product;
  /**
   * Optional header content for the features section
   */
  header?: {
    /**
     * Section title (optional)
     */
    title?: string | null;
    /**
     * Section subtitle (optional)
     */
    subtitle?: string | null;
    /**
     * Section description (optional)
     */
    description?: string | null;
  };
  /**
   * List of features to display
   */
  features: {
    /**
     * Icon configuration for this feature
     */
    icon?: {
      /**
       * Type of icon to display
       */
      type?: ('none' | 'image' | 'icon' | 'emoji') | null;
      /**
       * Custom icon image
       */
      image?: (string | null) | Media;
      /**
       * Icon name (e.g., "check", "star", "music")
       */
      iconName?: string | null;
      /**
       * Emoji character (e.g., "🎹", "✨", "🎵")
       */
      emoji?: string | null;
    };
    /**
     * Feature title/name
     */
    title: string;
    /**
     * Feature description (optional)
     */
    description?: string | null;
    /**
     * Highlight this feature with special styling
     */
    highlight?: boolean | null;
    id?: string | null;
  }[];
  /**
   * Layout and styling options
   */
  layout?: {
    /**
     * Display style for features
     */
    style?: ('grid' | 'list' | 'cards' | 'minimal') | null;
    /**
     * Number of columns for grid/cards layouts
     */
    columns?: ('one' | 'two' | 'three' | 'four') | null;
    /**
     * Position of icons relative to text
     */
    iconPosition?: ('left' | 'top' | 'right') | null;
    /**
     * Spacing between features
     */
    spacing?: ('compact' | 'medium' | 'spacious') | null;
    /**
     * Background color for the features section
     */
    backgroundColor?: ('none' | 'light-gray' | 'dark-gray' | 'brand' | 'accent') | null;
  };
  /**
   * Show numbered list (1, 2, 3...) instead of icons
   */
  showNumbers?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featuresList';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SpecificationsBlock".
 */
export interface SpecificationsBlock {
  /**
   * Choose data source for specifications
   */
  dataSource?: ('manual' | 'pianomodel' | 'hybrid') | null;
  /**
   * Select piano model to automatically populate specifications
   */
  pianoModel?: (string | null) | Product;
  /**
   * Header content for the specifications section
   */
  header?: {
    /**
     * Section title
     */
    title?: string | null;
    /**
     * Optional description above specifications
     */
    description?: string | null;
  };
  /**
   * Additional specification categories (leave empty to use Piano Model specifications only)
   */
  categories?:
    | {
        /**
         * Category name (e.g., "Dimensions", "Sound", "Features")
         */
        categoryName: string;
        /**
         * Individual specifications within this category
         */
        specifications: {
          /**
           * Specification label (e.g., "Width", "Polyphony", "Weight")
           */
          label: string;
          /**
           * Specification value (e.g., "145cm", "256 notes", "68kg")
           */
          value: string;
          /**
           * Highlight this specification as important
           */
          highlight?: boolean | null;
          /**
           * Additional note or context (optional)
           */
          note?: string | null;
          id?: string | null;
        }[];
        /**
         * Make this category collapsible/expandable
         */
        collapsible?: boolean | null;
        /**
         * Start expanded (only applies if collapsible is enabled)
         */
        defaultExpanded?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Layout and styling options
   */
  layout?: {
    /**
     * Display style for specifications
     */
    style?: ('table' | 'cards' | 'list' | 'grid') | null;
    /**
     * Number of columns for categories
     */
    columns?: ('one' | 'two' | 'three') | null;
    /**
     * Show icons next to category names
     */
    showCategoryIcons?: boolean | null;
    /**
     * Alternate row colors for better readability
     */
    alternateRows?: boolean | null;
    /**
     * Use compact spacing for dense information display
     */
    compactMode?: boolean | null;
  };
  /**
   * Options for downloading detailed specifications
   */
  downloadOptions?: {
    /**
     * Allow users to download specifications as PDF/document
     */
    enableDownload?: boolean | null;
    /**
     * Specifications document to download
     */
    downloadFile?: (string | null) | Media;
    /**
     * Download button text
     */
    downloadButtonText?: string | null;
  };
  /**
   * Enable comparison view (useful for product comparison pages)
   */
  comparisonMode?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'specifications';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  /**
   * Main content for the call-to-action
   */
  content: {
    /**
     * Main CTA title/headline
     */
    title: string;
    /**
     * Optional subtitle or supporting text
     */
    subtitle?: string | null;
    /**
     * CTA description or value proposition
     */
    description?: string | null;
  };
  /**
   * Action buttons for the CTA
   */
  buttons: {
    /**
     * Button text
     */
    text: string;
    /**
     * Button link/URL
     */
    link: string;
    /**
     * Button visual style
     */
    style?: ('primary' | 'secondary' | 'outline' | 'ghost' | 'link') | null;
    /**
     * Button size
     */
    size?: ('small' | 'medium' | 'large') | null;
    /**
     * Optional icon name (e.g., "arrow-right", "download", "phone")
     */
    icon?: string | null;
    /**
     * Icon position relative to text
     */
    iconPosition?: ('left' | 'right') | null;
    /**
     * Open link in new tab
     */
    openInNewTab?: boolean | null;
    id?: string | null;
  }[];
  /**
   * Media and visual elements
   */
  media?: {
    /**
     * Type of media to include
     */
    type?: ('none' | 'background' | 'side' | 'icon') | null;
    /**
     * Background image for the CTA section
     */
    backgroundImage?: (string | null) | Media;
    /**
     * Side image to display alongside content
     */
    sideImage?: (string | null) | Media;
    /**
     * Icon name (e.g., "star", "heart", "trophy")
     */
    iconName?: string | null;
    /**
     * Position of side image relative to content
     */
    imagePosition?: ('left' | 'right') | null;
    /**
     * Background overlay settings
     */
    overlay?: {
      /**
       * Add overlay to improve text readability
       */
      enable?: boolean | null;
      color?: ('dark' | 'light' | 'brand') | null;
      /**
       * Overlay opacity
       */
      opacity?: number | null;
    };
  };
  /**
   * Layout and styling options
   */
  layout?: {
    /**
     * Overall CTA design style
     */
    style?: ('banner' | 'card' | 'minimal' | 'split') | null;
    /**
     * Content alignment
     */
    alignment?: ('left' | 'center' | 'right') | null;
    /**
     * CTA section size/padding
     */
    size?: ('small' | 'medium' | 'large') | null;
    /**
     * Background color for the CTA section
     */
    backgroundColor?: ('none' | 'light-gray' | 'dark-gray' | 'brand' | 'accent' | 'gradient') | null;
    /**
     * Button arrangement when multiple buttons are present
     */
    buttonLayout?: ('horizontal' | 'vertical') | null;
  };
  /**
   * Urgency and scarcity elements
   */
  urgency?: {
    /**
     * Add urgency elements (countdown, limited time, etc.)
     */
    enableUrgency?: boolean | null;
    /**
     * Urgency message (e.g., "Limited time offer", "Only 3 left in stock")
     */
    urgencyText?: string | null;
    /**
     * Show countdown timer
     */
    showCountdown?: boolean | null;
    /**
     * Countdown end date and time
     */
    countdownEndDate?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'callToAction';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock".
 */
export interface TestimonialsBlock {
  /**
   * Header content for the testimonials section
   */
  header?: {
    /**
     * Section title
     */
    title?: string | null;
    /**
     * Optional subtitle
     */
    subtitle?: string | null;
    /**
     * Optional description above testimonials
     */
    description?: string | null;
  };
  /**
   * Customer testimonials and reviews
   */
  testimonials: {
    /**
     * Customer testimonial/review text
     */
    quote: string;
    /**
     * Star rating (1-5 stars, optional)
     */
    rating?: number | null;
    /**
     * Customer information
     */
    customer: {
      /**
       * Customer name
       */
      name: string;
      /**
       * Customer title/position (optional)
       */
      title?: string | null;
      /**
       * Customer company/organization (optional)
       */
      company?: string | null;
      /**
       * Customer location (optional)
       */
      location?: string | null;
      /**
       * Customer photo/avatar (optional)
       */
      avatar?: (string | null) | Media;
    };
    /**
     * Product being reviewed (optional)
     */
    product?: string | null;
    /**
     * Mark as verified purchase/review
     */
    verified?: boolean | null;
    /**
     * Feature this testimonial prominently
     */
    featured?: boolean | null;
    /**
     * Source of the review (optional)
     */
    source?: ('direct' | 'google' | 'facebook' | 'trustpilot' | 'yelp' | 'amazon' | 'other') | null;
    /**
     * Date of review (optional)
     */
    reviewDate?: string | null;
    id?: string | null;
  }[];
  /**
   * Layout and display options
   */
  layout?: {
    /**
     * Display style for testimonials
     */
    style?: ('cards' | 'carousel' | 'grid' | 'list' | 'masonry') | null;
    /**
     * Number of columns for grid/card layouts
     */
    columns?: ('one' | 'two' | 'three' | 'four') | null;
    /**
     * Display customer avatars/photos
     */
    showAvatars?: boolean | null;
    /**
     * Display star ratings
     */
    showRatings?: boolean | null;
    /**
     * Show review source (Google, Facebook, etc.)
     */
    showSource?: boolean | null;
    /**
     * Show review dates
     */
    showDates?: boolean | null;
    /**
     * Background color for the testimonials section
     */
    backgroundColor?: ('none' | 'light-gray' | 'dark-gray' | 'brand' | 'white') | null;
  };
  /**
   * Carousel-specific settings
   */
  carouselSettings?: {
    /**
     * Auto-advance testimonials
     */
    autoplay?: boolean | null;
    /**
     * Autoplay speed in milliseconds
     */
    autoplaySpeed?: number | null;
    /**
     * Show navigation dots
     */
    showDots?: boolean | null;
    /**
     * Show navigation arrows
     */
    showArrows?: boolean | null;
    /**
     * Number of testimonials to show at once
     */
    slidesToShow?: ('one' | 'two' | 'three') | null;
    /**
     * Enable infinite loop
     */
    infinite?: boolean | null;
  };
  /**
   * Overall rating and review summary
   */
  aggregateRating?: {
    /**
     * Show overall rating summary
     */
    showOverallRating?: boolean | null;
    /**
     * Overall rating score
     */
    overallRating?: number | null;
    /**
     * Total number of reviews
     */
    totalReviews?: number | null;
    /**
     * Rating description (e.g., "Excellent", "Based on 150 reviews")
     */
    ratingText?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonials';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HelloBlock".
 */
export interface HelloBlock {
  /**
   * The message to display
   */
  message: string;
  /**
   * Display current timestamp with the message
   */
  showTimestamp?: boolean | null;
  /**
   * Format for the timestamp display
   */
  timestampFormat?: ('datetime' | 'date' | 'time' | 'relative') | null;
  /**
   * Styling options for the hello block
   */
  style?: {
    /**
     * Text size for the message
     */
    textSize?: ('small' | 'medium' | 'large' | 'xl') | null;
    /**
     * Text alignment
     */
    textAlign?: ('left' | 'center' | 'right') | null;
    /**
     * Background color for the hello block
     */
    backgroundColor?: ('none' | 'light-gray' | 'dark-gray' | 'brand' | 'accent') | null;
    /**
     * Padding around the content
     */
    padding?: ('none' | 'small' | 'medium' | 'large') | null;
  };
  /**
   * Additional content options
   */
  additionalContent?: {
    /**
     * Show additional description text
     */
    showDescription?: boolean | null;
    /**
     * Additional description or context
     */
    description?: string | null;
    /**
     * Display an icon with the message
     */
    showIcon?: boolean | null;
    /**
     * Icon name (e.g., "wave", "smile", "star")
     */
    icon?: string | null;
    /**
     * Position of icon relative to message
     */
    iconPosition?: ('left' | 'right' | 'above' | 'below') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'hello';
}
/**
 * User accounts and authentication management
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  /**
   * User role for access control
   */
  role: 'admin' | 'user';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * Manage all content for the homepage including hero, showroom location, piano collection, gallery, news, contact form, and SEO.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: string;
  /**
   * Location/Piano Gallery status text displayed at the top
   */
  locationText: string;
  /**
   * Established date and location information
   */
  establishedText: string;
  /**
   * Title prefix word (e.g., "The")
   */
  titlePrefix: string;
  /**
   * Main title word - typically displayed prominently
   */
  titleMain: string;
  /**
   * Title suffix words (e.g., "to Life")
   */
  titleSuffix: string;
  /**
   * Hero description text displayed below the main title
   */
  description: string;
  /**
   * Primary call-to-action button configuration
   */
  primaryCta: {
    /**
     * Primary call-to-action button text
     */
    text: string;
    /**
     * Primary call-to-action button link/URL
     */
    link: string;
  };
  /**
   * Secondary call-to-action button configuration
   */
  secondaryCta: {
    /**
     * Secondary call-to-action button text
     */
    text: string;
    /**
     * Secondary call-to-action button link/URL
     */
    link: string;
  };
  /**
   * Background video for the hero section
   */
  backgroundVideo?: (string | null) | Media;
  /**
   * Section header text
   */
  sectionHeader: string;
  /**
   * Main showroom section title
   */
  showroomTitle: string;
  /**
   * Showroom section description
   */
  showroomDescription: string;
  /**
   * Basic showroom contact and location information
   */
  showroomInfo: {
    /**
     * Business/showroom name
     */
    name: string;
    /**
     * Full business address
     */
    address: string;
    /**
     * Primary phone number
     */
    phone: string;
    /**
     * Service area description
     */
    serviceArea: string;
  };
  /**
   * Showroom operating hours for each day of the week
   */
  hours: {
    /**
     * Day of the week (e.g., "Monday", "Tuesday")
     */
    day: string;
    /**
     * Hours for this day (e.g., "10:00 AM - 7:00 PM", "Closed")
     */
    time: string;
    id?: string | null;
  }[];
  /**
   * Key features and services offered at the showroom
   */
  features: {
    /**
     * Icon to display for this feature
     */
    icon: 'piano' | 'music' | 'award' | 'users' | 'clock' | 'shield' | 'headphones' | 'car';
    /**
     * Feature title (e.g., "Expert Consultation")
     */
    title: string;
    /**
     * Feature description
     */
    description: string;
    id?: string | null;
  }[];
  /**
   * Google Maps API key for embedded map (optional)
   */
  mapApiKey?: string | null;
  /**
   * Call-to-action buttons for the showroom section
   */
  showroomCtas: {
    /**
     * Directions button text
     */
    directionsText: string;
    /**
     * Google Maps directions link
     */
    directionsLink: string;
    /**
     * Schedule visit button text
     */
    scheduleText: string;
    /**
     * Schedule visit link/URL
     */
    scheduleLink: string;
  };
  /**
   * Piano collection section header
   */
  collectionSectionHeader: string;
  /**
   * Featured collection title
   */
  collectionTitle: string;
  /**
   * Featured collection description
   */
  collectionDescription: string;
  /**
   * Call-to-action for the piano collection section
   */
  collectionCta: {
    /**
     * Collection CTA button text
     */
    text: string;
    /**
     * Collection CTA button link/URL
     */
    link: string;
  };
  /**
   * Featured video configuration for the collection section
   */
  featuredVideo?: {
    /**
     * YouTube video ID for featured video
     */
    youtubeId?: string | null;
    /**
     * Video player width
     */
    width?: number | null;
    /**
     * Video player height
     */
    height?: number | null;
  };
  /**
   * Piano gallery section title
   */
  galleryTitle: string;
  /**
   * Piano gallery section description
   */
  galleryDescription: string;
  /**
   * Piano categories displayed in the gallery section
   */
  pianoCategories: {
    /**
     * Piano model or series name (e.g., "GX-7", "CA99")
     */
    model: string;
    /**
     * Category title (e.g., "Concert Grand Pianos")
     */
    title: string;
    /**
     * Category description
     */
    description: string;
    /**
     * Category representative image
     */
    image?: (string | null) | Media;
    /**
     * Link to category or model page
     */
    href: string;
    id?: string | null;
  }[];
  /**
   * Auto-play duration in milliseconds (default: 7000ms = 7 seconds)
   */
  autoPlayDuration: number;
  /**
   * News carousel items
   */
  newsItems: {
    /**
     * News item title
     */
    title: string;
    /**
     * News item description
     */
    description: string;
    /**
     * News item image
     */
    image?: (string | null) | Media;
    /**
     * News item category
     */
    category: 'news' | 'events' | 'promotions' | 'new-arrivals' | 'education';
    /**
     * Link to full article or page (optional)
     */
    link?: string | null;
    id?: string | null;
  }[];
  /**
   * Contact form section title (first part)
   */
  contactTitle: string;
  /**
   * Contact form section title highlight word
   */
  contactTitleHighlight: string;
  /**
   * Contact form section description
   */
  contactDescription: string;
  /**
   * Step titles for the contact process
   */
  stepTitles: {
    step: string;
    id?: string | null;
  }[];
  /**
   * Trust/credibility message
   */
  trustMessage: string;
  /**
   * Benefits/features of working with your Piano Gallery
   */
  benefits: {
    /**
     * Benefit icon
     */
    icon: 'shield-check' | 'clock' | 'users' | 'award' | 'music' | 'heart';
    /**
     * Benefit text
     */
    text: string;
    id?: string | null;
  }[];
  /**
   * Form field options and choices
   */
  formOptions: {
    /**
     * Musical experience level options
     */
    experienceLevels: {
      level: string;
      id?: string | null;
    }[];
    /**
     * Piano type options for the form
     */
    pianoTypes: {
      type: string;
      id?: string | null;
    }[];
    /**
     * Budget range options for the form
     */
    budgetRanges: {
      range: string;
      id?: string | null;
    }[];
    /**
     * Primary use options for the piano
     */
    primaryUses: {
      use: string;
      id?: string | null;
    }[];
  };
  /**
   * SEO and metadata configuration
   */
  seo?: {
    /**
     * Page meta title for search engines
     */
    metaTitle?: string | null;
    /**
     * Page meta description for search engines (max 160 characters)
     */
    metaDescription?: string | null;
    /**
     * SEO keywords (comma-separated)
     */
    keywords?: string | null;
    /**
     * Open Graph title for social media sharing
     */
    openGraphTitle?: string | null;
    /**
     * Open Graph description for social media sharing
     */
    openGraphDescription?: string | null;
    /**
     * Open Graph image for social media sharing
     */
    openGraphImage?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage all content for the main Pianos page including hero, categories, featured models, and CTAs.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pianos-page".
 */
export interface PianosPage {
  id: string;
  /**
   * Main page title displayed in the hero section
   */
  heroTitle: string;
  /**
   * Hero description text displayed below the title
   */
  heroDescription: string;
  /**
   * Background image for the hero section
   */
  heroBackgroundImage?: (string | null) | Media;
  /**
   * Hero call-to-action button configuration
   */
  heroCta: {
    /**
     * Call-to-action button text
     */
    text: string;
    /**
     * Call-to-action button link/URL
     */
    link: string;
  };
  /**
   * The four main piano categories displayed on the page
   */
  pianoCategories: {
    /**
     * URL slug for this category (e.g., "grand", "digital")
     */
    slug: string;
    /**
     * Category display name (e.g., "Acoustic Grand Pianos")
     */
    name: string;
    /**
     * Category description text
     */
    description: string;
    /**
     * Category representative image
     */
    image?: (string | null) | Media;
    /**
     * Price range for this category (e.g., "$45,000 - $185,000")
     */
    priceRange?: string | null;
    /**
     * Key features of this piano category
     */
    features?:
      | {
          feature: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Icon to display for this category
     */
    icon?: ('piano' | 'music' | 'zap' | 'award' | 'crown') | null;
    /**
     * Badge text (e.g., "Professional", "Classic")
     */
    badge?: string | null;
    /**
     * Highlighted feature or series (e.g., "GX BLAK Performance Series")
     */
    highlight?: string | null;
    /**
     * First showcase image for this piano category
     */
    galleryImage1?: (string | null) | Media;
    /**
     * Second showcase image for this piano category
     */
    galleryImage2?: (string | null) | Media;
    /**
     * Third showcase image for this piano category
     */
    galleryImage3?: (string | null) | Media;
    id?: string | null;
  }[];
  /**
   * Featured models section header content
   */
  featuredModelsSection: {
    /**
     * Section title for featured models
     */
    title: string;
    /**
     * Section description for featured models
     */
    description: string;
  };
  /**
   * Three featured piano models for the carousel
   */
  featuredModels: {
    /**
     * Piano model name (e.g., "GX-7 BLAK")
     */
    name: string;
    /**
     * Piano category/series (e.g., "GX BLAK Performance Series")
     */
    category: string;
    /**
     * Featured model image for carousel
     */
    image?: (string | null) | Media;
    /**
     * Badge text (e.g., "Performance Series", "Flagship Digital")
     */
    badge?: string | null;
    /**
     * Model description for carousel slide
     */
    description: string;
    id?: string | null;
  }[];
  /**
   * Final call-to-action section configuration
   */
  ctaSection: {
    /**
     * CTA section main title
     */
    title: string;
    /**
     * CTA section description text
     */
    description: string;
    /**
     * Call-to-action button text
     */
    ctaText: string;
    /**
     * Call-to-action button link/URL
     */
    ctaLink: string;
  };
  /**
   * SEO and metadata configuration
   */
  seo?: {
    /**
     * Page meta title for search engines
     */
    metaTitle?: string | null;
    /**
     * Page meta description for search engines (max 160 characters)
     */
    metaDescription?: string | null;
    /**
     * SEO keywords (comma-separated)
     */
    keywords?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage storefront locations with customizable content structure including hero, showroom information, piano collection, gallery, news, contact form, and SEO.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "storefronts".
 */
export interface Storefront {
  id: string;
  /**
   * URL-friendly identifier for this storefront location (e.g., "st-louis", "chicago")
   */
  slug: string;
  /**
   * Location name for admin identification (e.g., "St. Louis Showroom", "Chicago Downtown")
   */
  locationName: string;
  /**
   * Controls whether this storefront location is visible on the frontend
   */
  isActive?: boolean | null;
  /**
   * Location/Piano Gallery status text displayed at the top (include "Kawai" for brand visibility)
   */
  locationText: string;
  /**
   * Established date and location information
   */
  establishedText: string;
  /**
   * Hero description text displayed below the logo
   */
  description: string;
  /**
   * Primary call-to-action button configuration
   */
  primaryCta: {
    /**
     * Primary call-to-action button text
     */
    text: string;
    /**
     * Primary call-to-action button link/URL
     */
    link: string;
  };
  /**
   * Secondary call-to-action button configuration
   */
  secondaryCta: {
    /**
     * Secondary call-to-action button text
     */
    text: string;
    /**
     * Secondary call-to-action button link/URL
     */
    link: string;
  };
  /**
   * Background video for the hero section
   */
  backgroundVideo?: (string | null) | Media;
  /**
   * Section header text
   */
  sectionHeader: string;
  /**
   * Main showroom section title
   */
  showroomTitle: string;
  /**
   * Showroom section description
   */
  showroomDescription: string;
  /**
   * Basic showroom contact and location information
   */
  showroomInfo: {
    /**
     * Business/showroom name
     */
    name: string;
    /**
     * Full business address
     */
    address: string;
    /**
     * Primary phone number
     */
    phone: string;
    /**
     * Service area description
     */
    serviceArea: string;
  };
  /**
   * Showroom operating hours for each day of the week
   */
  hours: {
    /**
     * Day of the week (e.g., "Monday", "Tuesday")
     */
    day: string;
    /**
     * Hours for this day (e.g., "10:00 AM - 7:00 PM", "Closed")
     */
    time: string;
    id?: string | null;
  }[];
  /**
   * Key features and services offered at the showroom
   */
  features: {
    /**
     * Icon to display for this feature
     */
    icon: 'piano' | 'music' | 'award' | 'users' | 'clock' | 'shield' | 'headphones' | 'car';
    /**
     * Feature title (e.g., "Expert Consultation")
     */
    title: string;
    /**
     * Feature description
     */
    description: string;
    id?: string | null;
  }[];
  /**
   * Google Maps API key for embedded map (optional)
   */
  mapApiKey?: string | null;
  /**
   * Call-to-action buttons for the showroom section
   */
  showroomCtas: {
    /**
     * Directions button text
     */
    directionsText: string;
    /**
     * Google Maps directions link
     */
    directionsLink: string;
    /**
     * Schedule visit button text
     */
    scheduleText: string;
    /**
     * Schedule visit link/URL
     */
    scheduleLink: string;
  };
  /**
   * Service area information enables ranking in multiple cities without physical locations
   */
  serviceAreaCoverage: {
    /**
     * Main city where storefront is physically located
     */
    primaryCity: string;
    /**
     * List major cities within service radius (recommended: ~2 hour drive maximum). Used for local SEO targeting.
     */
    coveredCities?:
      | {
          cityName: string;
          /**
           * Approximate drive time from this city to showroom
           */
          driveTime?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Broader geographic region served (e.g., "Missouri & Southern Illinois")
     */
    stateRegion: string;
    /**
     * Comma-separated list of primary zip codes in service area
     */
    zipCodes?: string | null;
  };
  /**
   * Piano collection section header
   */
  collectionSectionHeader: string;
  /**
   * Featured collection title
   */
  collectionTitle: string;
  /**
   * Featured collection description
   */
  collectionDescription: string;
  /**
   * Call-to-action for the piano collection section
   */
  collectionCta: {
    /**
     * Collection CTA button text
     */
    text: string;
    /**
     * Collection CTA button link/URL
     */
    link: string;
  };
  /**
   * Featured video configuration for the collection section
   */
  featuredVideo?: {
    /**
     * YouTube video ID for featured video
     */
    youtubeId?: string | null;
    /**
     * Video player width
     */
    width?: number | null;
    /**
     * Video player height
     */
    height?: number | null;
  };
  /**
   * Auto-play duration in milliseconds (leave empty to use main site default)
   */
  autoPlayDuration?: number | null;
  /**
   * News carousel items (leave empty to use main site news)
   */
  newsItems?:
    | {
        /**
         * News item title
         */
        title: string;
        /**
         * News item description
         */
        description: string;
        /**
         * News item image
         */
        image?: (string | null) | Media;
        /**
         * News item category
         */
        category: 'news' | 'events' | 'promotions' | 'new-arrivals' | 'education';
        /**
         * Link to full article or page (optional)
         */
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Add location-specific customer testimonials. This section will only display on the storefront page if at least one testimonial is added. Prioritize local customers for maximum relevance.
   */
  customerTestimonials?:
    | {
        /**
         * Full name of customer (first and last name recommended)
         */
        customerName: string;
        /**
         * City and state for local relevance (e.g., "Clayton, MO")
         */
        customerCity: string;
        /**
         * Star rating (1-5 stars)
         */
        rating: number;
        /**
         * Customer testimonial text (150-300 words ideal for authenticity and SEO)
         */
        testimonialText: string;
        /**
         * Piano model purchased (adds specificity and credibility)
         */
        pianoModel?: string | null;
        /**
         * Date of purchase (shows recency)
         */
        purchaseDate?: string | null;
        /**
         * Photo of customer with their piano (optional but powerful for trust)
         */
        customerPhoto?: (string | null) | Media;
        /**
         * Video testimonial (converts 10x better than text, optional)
         */
        videoTestimonial?: (string | null) | Media;
        /**
         * Display this testimonial first/prominently on the page
         */
        featured?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Contact form section title (first part)
   */
  contactTitle: string;
  /**
   * Contact form section title highlight word
   */
  contactTitleHighlight: string;
  /**
   * Contact form section description
   */
  contactDescription: string;
  /**
   * Step titles for the contact process
   */
  stepTitles: {
    step: string;
    id?: string | null;
  }[];
  /**
   * Trust/credibility message
   */
  trustMessage: string;
  /**
   * Benefits/features of working with your Piano Gallery
   */
  benefits: {
    /**
     * Benefit icon
     */
    icon: 'shield-check' | 'clock' | 'users' | 'award' | 'music' | 'heart';
    /**
     * Benefit text
     */
    text: string;
    id?: string | null;
  }[];
  /**
   * Form field options and choices
   */
  formOptions: {
    /**
     * Musical experience level options
     */
    experienceLevels: {
      level: string;
      id?: string | null;
    }[];
    /**
     * Piano type options for the form
     */
    pianoTypes: {
      type: string;
      id?: string | null;
    }[];
    /**
     * Budget range options for the form
     */
    budgetRanges: {
      range: string;
      id?: string | null;
    }[];
    /**
     * Primary use options for the piano
     */
    primaryUses: {
      use: string;
      id?: string | null;
    }[];
  };
  /**
   * Schema.org structured data improves search result appearance and local SEO rankings
   */
  schemaData: {
    /**
     * Indicates relative pricing level for schema.org MusicStore type
     */
    priceRange: '$' | '$$' | '$$$' | '$$$$';
    /**
     * Exact GPS coordinates for map placement and local search. Find coordinates at https://www.latlong.net/
     */
    geoCoordinates: {
      /**
       * Latitude coordinate (e.g., 38.627003)
       */
      latitude: number;
      /**
       * Longitude coordinate (e.g., -90.199402)
       */
      longitude: number;
    };
    /**
     * Payment methods accepted at this location (used in schema markup)
     */
    paymentMethods: {
      method:
        | 'Cash'
        | 'Credit Card'
        | 'Debit Card'
        | 'Financing'
        | 'Check'
        | 'Wire Transfer'
        | 'Apple Pay'
        | 'Google Pay';
      id?: string | null;
    }[];
    /**
     * Date business was founded (e.g., 1985-03-15). Displays as "Est. 1985" and builds trust through longevity.
     */
    foundingDate?: string | null;
  };
  /**
   * SEO and metadata configuration
   */
  seo?: {
    /**
     * Page meta title for search engines (leave empty to auto-generate "KAWAI [City Name]" from storefront name)
     */
    metaTitle?: string | null;
    /**
     * Page meta description for search engines (max 160 characters, leave empty for auto-generated description)
     */
    metaDescription?: string | null;
    /**
     * SEO keywords (comma-separated)
     */
    keywords?: string | null;
    /**
     * Open Graph title for social media sharing
     */
    openGraphTitle?: string | null;
    /**
     * Open Graph description for social media sharing
     */
    openGraphDescription?: string | null;
    /**
     * Open Graph image for social media sharing
     */
    openGraphImage?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage Concert Artist page content - models overview and image gallery
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "concert-artist-page".
 */
export interface ConcertArtistPage {
  id: string;
  /**
   * Internal title for admin identification
   */
  pageTitle: string;
  modelsOverviewSection: {
    /**
     * Section header eyebrow text
     */
    sectionHeader: string;
    /**
     * Section main title
     */
    sectionTitle: string;
  };
  /**
   * Four Concert Artist models displayed in the overview section
   */
  concertArtistModels: {
    /**
     * Model name (e.g., "CA401", "CA501")
     */
    name: string;
    /**
     * Model tagline (e.g., "Where Mastery Begins")
     */
    tagline: string;
    /**
     * Brief model description (1-2 sentences)
     */
    descriptor: string;
    /**
     * Model showcase image
     */
    image?: (string | null) | Media;
    /**
     * Link to product page (e.g., "/products/ca401")
     */
    link: string;
    id?: string | null;
  }[];
  /**
   * Image galleries for all four Concert Artist models
   */
  modelGalleries: {
    /**
     * Model identifier
     */
    modelId: 'ca401' | 'ca501' | 'ca701' | 'ca901';
    /**
     * Model name display (e.g., "CA401")
     */
    modelName: string;
    /**
     * Model tagline for gallery tab
     */
    tagline: string;
    /**
     * Six showcase images for this model
     */
    images: {
      /**
       * Gallery image
       */
      image?: (string | null) | Media;
      /**
       * Image alt text for accessibility
       */
      alt: string;
      id?: string | null;
    }[];
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage Constant Contact API credentials and OAuth2 tokens. Restricted to admin users only.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "constant-contact-settings".
 */
export interface ConstantContactSetting {
  id: string;
  /**
   * Your Constant Contact Client ID from the developer portal
   */
  clientId: string;
  /**
   * Your Constant Contact Client Secret from the developer portal
   */
  clientSecret: string;
  /**
   * The redirect URI configured in your Constant Contact app
   */
  redirectUri: string;
  /**
   * Constant Contact API base URL (usually https://api.cc.email/v3)
   */
  baseUrl?: string | null;
  /**
   * Current access token for API requests
   */
  accessToken?: string | null;
  /**
   * Refresh token for obtaining new access tokens
   */
  refreshToken?: string | null;
  /**
   * Token type (typically "Bearer")
   */
  tokenType?: string | null;
  /**
   * OAuth2 scopes granted to the application
   */
  scope?: string | null;
  /**
   * When the current access token expires
   */
  expiresAt?: string | null;
  /**
   * Current status of the API connection
   */
  status: 'pending_authorization' | 'active' | 'expired' | 'refresh_failed' | 'error';
  /**
   * Timestamp of the last successful API request
   */
  lastSuccessfulRequest?: string | null;
  /**
   * Timestamp of the last token refresh
   */
  lastTokenRefresh?: string | null;
  /**
   * Last error message (if any)
   */
  errorMessage?: string | null;
  /**
   * Additional notes or configuration details
   */
  notes?: string | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * Custom field ID mappings for Constant Contact API integration
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "constant-contact-custom-fields".
 */
export interface ConstantContactCustomField {
  id: string;
  /**
   * Internal field name used in code (e.g., student_first_name)
   */
  fieldName: string;
  /**
   * Human-readable label shown in Constant Contact UI
   */
  fieldLabel: string;
  /**
   * Constant Contact API custom field ID (auto-populated)
   */
  customFieldId: string;
  /**
   * Data type for this custom field
   */
  fieldType: 'string' | 'date' | 'single_select' | 'multi_select';
  /**
   * Whether this field exists in Constant Contact
   */
  createdInConstantContact?: boolean | null;
  /**
   * Last time this field was verified with Constant Contact
   */
  lastSyncedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'home-page';
        value: string | HomePage;
      } | null)
    | ({
        relationTo: 'pianos-page';
        value: string | PianosPage;
      } | null)
    | ({
        relationTo: 'storefronts';
        value: string | Storefront;
      } | null)
    | ({
        relationTo: 'concert-artist-page';
        value: string | ConcertArtistPage;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'productlines';
        value: string | Productline;
      } | null)
    | ({
        relationTo: 'constant-contact-settings';
        value: string | ConstantContactSetting;
      } | null)
    | ({
        relationTo: 'constant-contact-custom-fields';
        value: string | ConstantContactCustomField;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  description?: T;
  mediaType?: T;
  usage?: T;
  videoMeta?:
    | T
    | {
        duration?: T;
        thumbnail?: T;
        autoplay?: T;
        muted?: T;
      };
  variants?:
    | T
    | {
        mobile?: T;
        tablet?: T;
        desktop?: T;
        largeDesktop?: T;
      };
  seoMeta?:
    | T
    | {
        focusKeywords?: T;
        photographerCredit?: T;
        copyrightInfo?: T;
        originalSource?: T;
      };
  featured?: T;
  tags?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        desktop?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  locationText?: T;
  establishedText?: T;
  titlePrefix?: T;
  titleMain?: T;
  titleSuffix?: T;
  description?: T;
  primaryCta?:
    | T
    | {
        text?: T;
        link?: T;
      };
  secondaryCta?:
    | T
    | {
        text?: T;
        link?: T;
      };
  backgroundVideo?: T;
  sectionHeader?: T;
  showroomTitle?: T;
  showroomDescription?: T;
  showroomInfo?:
    | T
    | {
        name?: T;
        address?: T;
        phone?: T;
        serviceArea?: T;
      };
  hours?:
    | T
    | {
        day?: T;
        time?: T;
        id?: T;
      };
  features?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  mapApiKey?: T;
  showroomCtas?:
    | T
    | {
        directionsText?: T;
        directionsLink?: T;
        scheduleText?: T;
        scheduleLink?: T;
      };
  collectionSectionHeader?: T;
  collectionTitle?: T;
  collectionDescription?: T;
  collectionCta?:
    | T
    | {
        text?: T;
        link?: T;
      };
  featuredVideo?:
    | T
    | {
        youtubeId?: T;
        width?: T;
        height?: T;
      };
  galleryTitle?: T;
  galleryDescription?: T;
  pianoCategories?:
    | T
    | {
        model?: T;
        title?: T;
        description?: T;
        image?: T;
        href?: T;
        id?: T;
      };
  autoPlayDuration?: T;
  newsItems?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        category?: T;
        link?: T;
        id?: T;
      };
  contactTitle?: T;
  contactTitleHighlight?: T;
  contactDescription?: T;
  stepTitles?:
    | T
    | {
        step?: T;
        id?: T;
      };
  trustMessage?: T;
  benefits?:
    | T
    | {
        icon?: T;
        text?: T;
        id?: T;
      };
  formOptions?:
    | T
    | {
        experienceLevels?:
          | T
          | {
              level?: T;
              id?: T;
            };
        pianoTypes?:
          | T
          | {
              type?: T;
              id?: T;
            };
        budgetRanges?:
          | T
          | {
              range?: T;
              id?: T;
            };
        primaryUses?:
          | T
          | {
              use?: T;
              id?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        openGraphTitle?: T;
        openGraphDescription?: T;
        openGraphImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pianos-page_select".
 */
export interface PianosPageSelect<T extends boolean = true> {
  heroTitle?: T;
  heroDescription?: T;
  heroBackgroundImage?: T;
  heroCta?:
    | T
    | {
        text?: T;
        link?: T;
      };
  pianoCategories?:
    | T
    | {
        slug?: T;
        name?: T;
        description?: T;
        image?: T;
        priceRange?: T;
        features?:
          | T
          | {
              feature?: T;
              id?: T;
            };
        icon?: T;
        badge?: T;
        highlight?: T;
        galleryImage1?: T;
        galleryImage2?: T;
        galleryImage3?: T;
        id?: T;
      };
  featuredModelsSection?:
    | T
    | {
        title?: T;
        description?: T;
      };
  featuredModels?:
    | T
    | {
        name?: T;
        category?: T;
        image?: T;
        badge?: T;
        description?: T;
        id?: T;
      };
  ctaSection?:
    | T
    | {
        title?: T;
        description?: T;
        ctaText?: T;
        ctaLink?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "storefronts_select".
 */
export interface StorefrontsSelect<T extends boolean = true> {
  slug?: T;
  locationName?: T;
  isActive?: T;
  locationText?: T;
  establishedText?: T;
  description?: T;
  primaryCta?:
    | T
    | {
        text?: T;
        link?: T;
      };
  secondaryCta?:
    | T
    | {
        text?: T;
        link?: T;
      };
  backgroundVideo?: T;
  sectionHeader?: T;
  showroomTitle?: T;
  showroomDescription?: T;
  showroomInfo?:
    | T
    | {
        name?: T;
        address?: T;
        phone?: T;
        serviceArea?: T;
      };
  hours?:
    | T
    | {
        day?: T;
        time?: T;
        id?: T;
      };
  features?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  mapApiKey?: T;
  showroomCtas?:
    | T
    | {
        directionsText?: T;
        directionsLink?: T;
        scheduleText?: T;
        scheduleLink?: T;
      };
  serviceAreaCoverage?:
    | T
    | {
        primaryCity?: T;
        coveredCities?:
          | T
          | {
              cityName?: T;
              driveTime?: T;
              id?: T;
            };
        stateRegion?: T;
        zipCodes?: T;
      };
  collectionSectionHeader?: T;
  collectionTitle?: T;
  collectionDescription?: T;
  collectionCta?:
    | T
    | {
        text?: T;
        link?: T;
      };
  featuredVideo?:
    | T
    | {
        youtubeId?: T;
        width?: T;
        height?: T;
      };
  autoPlayDuration?: T;
  newsItems?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        category?: T;
        link?: T;
        id?: T;
      };
  customerTestimonials?:
    | T
    | {
        customerName?: T;
        customerCity?: T;
        rating?: T;
        testimonialText?: T;
        pianoModel?: T;
        purchaseDate?: T;
        customerPhoto?: T;
        videoTestimonial?: T;
        featured?: T;
        id?: T;
      };
  contactTitle?: T;
  contactTitleHighlight?: T;
  contactDescription?: T;
  stepTitles?:
    | T
    | {
        step?: T;
        id?: T;
      };
  trustMessage?: T;
  benefits?:
    | T
    | {
        icon?: T;
        text?: T;
        id?: T;
      };
  formOptions?:
    | T
    | {
        experienceLevels?:
          | T
          | {
              level?: T;
              id?: T;
            };
        pianoTypes?:
          | T
          | {
              type?: T;
              id?: T;
            };
        budgetRanges?:
          | T
          | {
              range?: T;
              id?: T;
            };
        primaryUses?:
          | T
          | {
              use?: T;
              id?: T;
            };
      };
  schemaData?:
    | T
    | {
        priceRange?: T;
        geoCoordinates?:
          | T
          | {
              latitude?: T;
              longitude?: T;
            };
        paymentMethods?:
          | T
          | {
              method?: T;
              id?: T;
            };
        foundingDate?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        openGraphTitle?: T;
        openGraphDescription?: T;
        openGraphImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "concert-artist-page_select".
 */
export interface ConcertArtistPageSelect<T extends boolean = true> {
  pageTitle?: T;
  modelsOverviewSection?:
    | T
    | {
        sectionHeader?: T;
        sectionTitle?: T;
      };
  concertArtistModels?:
    | T
    | {
        name?: T;
        tagline?: T;
        descriptor?: T;
        image?: T;
        link?: T;
        id?: T;
      };
  modelGalleries?:
    | T
    | {
        modelId?: T;
        modelName?: T;
        tagline?: T;
        images?:
          | T
          | {
              image?: T;
              alt?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  type?: T;
  name?: T;
  slug?: T;
  category?: T;
  status?: T;
  mainImage?: T;
  imageUrl?: T;
  description?: T;
  shortDescription?: T;
  learnMore?: T;
  price?:
    | T
    | {
        currency?: T;
        msrp?: T;
        salePrice?: T;
        priceRange?: T;
        priceText?: T;
        contactForPricing?: T;
        showPrice?: T;
      };
  finishes?:
    | T
    | {
        name?: T;
        image?: T;
        priceModifier?: T;
        available?: T;
        description?: T;
        imageUrl?: T;
        id?: T;
      };
  productline?: T;
  series?: T;
  model?: T;
  rating?: T;
  reviews?: T;
  badge?: T;
  highlight?: T;
  brand?: T;
  keyFeatures?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  specifications?:
    | T
    | {
        keys?: T;
        pedals?: T;
        voices?: T;
        polyphony?: T;
        actionType?: T;
        soundEngine?: T;
        dimensions?:
          | T
          | {
              width?: T;
              depth?: T;
              height?: T;
            };
        weight?: T;
        sku?: T;
        warranty?: T;
        origin?: T;
      };
  buyButton?:
    | T
    | {
        text?: T;
        link?: T;
        style?: T;
        showButton?: T;
      };
  discontinued?: T;
  viewer3D?:
    | T
    | {
        enabled?: T;
        viewerUrl?: T;
        modelParams?: T;
        autoOpen?: T;
        buttonText?: T;
      };
  pageContent?: T | {};
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        ogImage?: T;
      };
  visibility?:
    | T
    | {
        featured?: T;
        showInCatalog?: T;
        allowReviews?: T;
        sortOrder?: T;
      };
  inventory?:
    | T
    | {
        trackStock?: T;
        stockQuantity?: T;
        lowStockThreshold?: T;
        inStock?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productlines_select".
 */
export interface ProductlinesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  category?: T;
  description?: T;
  highlight?: T;
  image?: T;
  slides?:
    | T
    | {
        title?: T;
        image?: T;
        id?: T;
      };
  products?: T;
  featured?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "constant-contact-settings_select".
 */
export interface ConstantContactSettingsSelect<T extends boolean = true> {
  clientId?: T;
  clientSecret?: T;
  redirectUri?: T;
  baseUrl?: T;
  accessToken?: T;
  refreshToken?: T;
  tokenType?: T;
  scope?: T;
  expiresAt?: T;
  status?: T;
  lastSuccessfulRequest?: T;
  lastTokenRefresh?: T;
  errorMessage?: T;
  notes?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "constant-contact-custom-fields_select".
 */
export interface ConstantContactCustomFieldsSelect<T extends boolean = true> {
  fieldName?: T;
  fieldLabel?: T;
  customFieldId?: T;
  fieldType?: T;
  createdInConstantContact?: T;
  lastSyncedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}