/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {
    productShowcase: ProductShowcaseBlock;
    hero: HeroBlock;
    textContent: TextContentBlock;
    imageGallery: ImageGalleryBlock;
    featuresList: FeaturesListBlock;
    specifications: SpecificationsBlock;
    callToAction: CallToActionBlock;
    testimonials: TestimonialsBlock;
  };
  collections: {
    users: User;
    media: Media;
    productlines: Productline;
    'piano-models': PianoModel;
    'pianos-page': PianosPage;
    products: Product;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    productlines: {
      pianoModels: 'piano-models';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    productlines: ProductlinesSelect<false> | ProductlinesSelect<true>;
    'piano-models': PianoModelsSelect<false> | PianoModelsSelect<true>;
    'pianos-page': PianosPageSelect<false> | PianosPageSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductShowcaseBlock".
 */
export interface ProductShowcaseBlock {
  /**
   * Choose data source for product information
   */
  dataSource?: ('manual' | 'pianomodel' | 'hybrid') | null;
  /**
   * Select piano model to automatically populate product information
   */
  pianoModel?: (string | null) | PianoModel;
  /**
   * Product showcase configuration
   */
  product: {
    /**
     * Main product image (leave empty to use Piano Model image)
     */
    image?: (string | null) | Media;
    /**
     * Product title/name (leave empty to use Piano Model name)
     */
    title?: string | null;
    /**
     * Product description (leave empty to use Piano Model description)
     */
    description?: string | null;
    /**
     * Product pricing information (overrides Piano Model pricing when provided)
     */
    price?: {
      /**
       * Price currency (leave empty to use Piano Model currency)
       */
      currency?: ('USD' | 'EUR' | 'GBP' | 'CAD') | null;
      /**
       * Price amount (leave empty to use Piano Model pricing)
       */
      amount?: number | null;
      /**
       * Sale price (leave empty to use Piano Model sale price)
       */
      saleAmount?: number | null;
      /**
       * Custom price text (leave empty to use Piano Model price text)
       */
      priceText?: string | null;
    };
    /**
     * Available finish options (overrides Piano Model finishes when provided)
     */
    finishes?:
      | {
          /**
           * Finish name (e.g., "Ebony Polish", "White Satin")
           */
          name: string;
          /**
           * Finish sample image (optional)
           */
          image?: (string | null) | Media;
          /**
           * Price difference for this finish (+ or -)
           */
          priceModifier?: number | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Buy button configuration
     */
    buyButton: {
      /**
       * Button text
       */
      text: string;
      /**
       * Button link/URL (leave empty to disable button)
       */
      link?: string | null;
      /**
       * Button style
       */
      style?: ('primary' | 'secondary' | 'outline') | null;
      /**
       * Open link in new tab
       */
      openInNewTab?: boolean | null;
    };
    /**
     * Optional badge text (e.g., "Best Seller", "New", "Limited Edition")
     */
    badge?: string | null;
    /**
     * Is this product currently in stock?
     */
    inStock?: boolean | null;
  };
  /**
   * Layout and display options
   */
  layout?: {
    /**
     * Position of product image relative to content
     */
    imagePosition?: ('left' | 'right' | 'top' | 'bottom') | null;
    /**
     * Show available finishes in this block
     */
    showFinishes?: boolean | null;
    /**
     * Show pricing information in this block
     */
    showPrice?: boolean | null;
    /**
     * Use compact layout (smaller spacing, condensed content)
     */
    compact?: boolean | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'productShowcase';
}
/**
 * Piano models that can automatically generate product pages with blocks and content
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "piano-models".
 */
export interface PianoModel {
  id: string;
  /**
   * Piano model name (e.g., "CA901", "SK-EX")
   */
  name: string;
  /**
   * URL-friendly version of piano model name
   */
  slug: string;
  /**
   * Model number/identifier
   */
  model: string;
  /**
   * The product line/series this model belongs to
   */
  productline: string | Productline;
  /**
   * Brief model description
   */
  description: string;
  /**
   * Short description for listings
   */
  shortDescription?: string | null;
  /**
   * Main product image
   */
  image: string | Media;
  /**
   * Main selling points and key features
   */
  keyFeatures?:
    | {
        feature: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Technical specifications
   */
  specifications?: {
    /**
     * Number of keys
     */
    keys?: number | null;
    /**
     * Number of pedals
     */
    pedals?: number | null;
    /**
     * Number of voices/sounds
     */
    voices?: number | null;
    /**
     * Maximum polyphony
     */
    polyphony?: number | null;
    dimensions?: {
      /**
       * Width (e.g., "145cm")
       */
      width?: string | null;
      /**
       * Depth (e.g., "46cm")
       */
      depth?: string | null;
      /**
       * Height (e.g., "88cm")
       */
      height?: string | null;
    };
    /**
     * Weight (e.g., "68kg")
     */
    weight?: string | null;
    /**
     * Action technology (e.g., "Grand Feel III")
     */
    actionType?: string | null;
    /**
     * Sound engine technology
     */
    soundEngine?: string | null;
  };
  /**
   * Available finish options for this piano model
   */
  availableFinishes?:
    | {
        /**
         * Finish name (e.g., "Ebony Polish", "White Satin")
         */
        name: string;
        /**
         * Finish sample image
         */
        image?: (string | null) | Media;
        /**
         * Price difference for this finish (+ or -)
         */
        priceModifier?: number | null;
        /**
         * Is this finish currently available?
         */
        available?: boolean | null;
        /**
         * Optional finish description
         */
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Pricing information
   */
  pricing?: {
    /**
     * Price currency
     */
    currency?: ('USD' | 'EUR' | 'GBP' | 'CAD') | null;
    /**
     * MSRP in selected currency
     */
    msrp?: number | null;
    /**
     * Sale price if different from MSRP
     */
    salePrice?: number | null;
    /**
     * Price range text (e.g., "$15,000 - $20,000")
     */
    priceRange?: string | null;
    /**
     * Custom price text (e.g., "Starting from", "Contact for pricing")
     */
    priceText?: string | null;
    /**
     * Check if pricing is by contact only
     */
    contactForPricing?: boolean | null;
    /**
     * Display price on product pages
     */
    showPrice?: boolean | null;
  };
  /**
   * Auto-generated product page for this piano model
   */
  product?: (string | null) | Product;
  /**
   * Automatically create/update a Product page when this piano model is saved
   */
  autoGenerateProduct?: boolean | null;
  /**
   * Status affects auto-generated product visibility
   */
  status?: ('active' | 'discontinued' | 'coming-soon' | 'limited-edition') | null;
  /**
   * Feature this model prominently
   */
  featured?: boolean | null;
  /**
   * Display order within series (lower numbers first)
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productlines".
 */
export interface Productline {
  id: string;
  /**
   * Series name (e.g., "CA Series", "Shigeru Kawai SK Series")
   */
  name: string;
  /**
   * URL-friendly version of name
   */
  slug: string;
  /**
   * Piano category for organizing series
   */
  category: 'digital' | 'grand' | 'hybrid' | 'upright';
  /**
   * Main series description for the browser
   */
  description: string;
  /**
   * Optional highlighted callout text
   */
  highlight?: string | null;
  /**
   * Main series image displayed in the browser (can be added after seeding)
   */
  image?: (string | null) | Media;
  /**
   * Additional slides for the clean series browser carousel
   */
  slides?:
    | {
        /**
         * Title for this slide
         */
        title: string;
        /**
         * Slide image (can be added after seeding)
         */
        image?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Piano models in this series (automatically populated)
   */
  pianoModels?: {
    docs?: (string | PianoModel)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Feature this series prominently
   */
  featured?: boolean | null;
  /**
   * Display order (lower numbers first)
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Alternative text for accessibility and SEO. Describe what the image shows.
   */
  alt: string;
  /**
   * Optional caption displayed with the image
   */
  caption?: string | null;
  /**
   * Detailed description for administrative purposes
   */
  description?: string | null;
  /**
   * Type of media for better organization
   */
  mediaType?: ('image' | 'video' | 'audio' | 'document') | null;
  /**
   * Where this media is intended to be used
   */
  usage?:
    | ('hero' | 'product' | 'category' | 'carousel' | 'background' | 'thumbnail' | 'technical' | 'marketing')[]
    | null;
  /**
   * Video-specific metadata
   */
  videoMeta?: {
    /**
     * Video duration in seconds
     */
    duration?: number | null;
    /**
     * Custom thumbnail for the video
     */
    thumbnail?: (string | null) | Media;
    /**
     * Should this video autoplay (use sparingly)
     */
    autoplay?: boolean | null;
    /**
     * Start video muted (recommended for autoplay)
     */
    muted?: boolean | null;
  };
  /**
   * Responsive image variants (generated automatically when uploaded)
   */
  variants?: {
    /**
     * Optimized for mobile devices (480px width)
     */
    mobile?: (string | null) | Media;
    /**
     * Optimized for tablets (768px width)
     */
    tablet?: (string | null) | Media;
    /**
     * Optimized for desktop (1200px width)
     */
    desktop?: (string | null) | Media;
    /**
     * Optimized for large screens (1920px width)
     */
    largeDesktop?: (string | null) | Media;
  };
  /**
   * SEO and technical metadata
   */
  seoMeta?: {
    /**
     * Keywords this image relates to (comma-separated)
     */
    focusKeywords?: string | null;
    /**
     * Photo credit information
     */
    photographerCredit?: string | null;
    /**
     * Copyright or licensing information
     */
    copyrightInfo?: string | null;
    /**
     * Original source or URL if external
     */
    originalSource?: string | null;
  };
  /**
   * Mark as featured media for easy access
   */
  featured?: boolean | null;
  /**
   * Tags for organization and search (e.g., "grand-piano", "black-finish")
   */
  tags?: string[] | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    desktop?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Manage products with dynamic page building capabilities using blocks
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  /**
   * Product type determines linking behavior and available features
   */
  type: 'piano' | 'other';
  /**
   * Link to piano model for automatic data population in blocks. When linked, some product data will auto-sync with the piano model.
   */
  pianoModel?: (string | null) | PianoModel;
  /**
   * How this product gets its content: Manual (independent), Piano Model (auto-synced), or Hybrid (manual with fallbacks)
   */
  dataSource?: ('manual' | 'pianomodel' | 'hybrid') | null;
  /**
   * Product name/title
   */
  name: string;
  /**
   * URL-friendly version of product name
   */
  slug: string;
  /**
   * Product category for organization
   */
  category: 'digital' | 'grand' | 'hybrid' | 'upright' | 'accessories' | 'software';
  /**
   * Product availability status
   */
  status?: ('active' | 'draft' | 'discontinued' | 'coming-soon' | 'limited-edition') | null;
  /**
   * Primary product image
   */
  mainImage: string | Media;
  /**
   * Product display title (can be different from name for SEO)
   */
  title: string;
  /**
   * Short product description for listings and meta
   */
  description: string;
  /**
   * Product pricing information
   */
  price?: {
    currency?: ('USD' | 'EUR' | 'GBP' | 'CAD') | null;
    /**
     * Regular price (leave empty for "Contact for pricing")
     */
    amount?: number | null;
    /**
     * Sale price (optional)
     */
    saleAmount?: number | null;
    /**
     * Custom price text (e.g., "Starting from", "Contact for pricing")
     */
    priceText?: string | null;
    /**
     * Display price on product pages
     */
    showPrice?: boolean | null;
  };
  /**
   * Available finish options
   */
  finishes?:
    | {
        /**
         * Finish name (e.g., "Ebony Polish", "White Satin")
         */
        name: string;
        /**
         * Finish sample image
         */
        image?: (string | null) | Media;
        /**
         * Price difference for this finish (+ or -)
         */
        priceModifier?: number | null;
        /**
         * Is this finish currently available?
         */
        available?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Buy button configuration
   */
  buyButton: {
    /**
     * Buy button text
     */
    text: string;
    /**
     * Buy button link (leave empty to use default contact form)
     */
    link?: string | null;
    style?: ('primary' | 'secondary' | 'outline') | null;
    /**
     * Show buy button on product pages
     */
    showButton?: boolean | null;
  };
  /**
   * Build your product page content using flexible blocks
   */
  pageContent?:
    | (
        | ProductShowcaseBlock
        | HeroBlock
        | TextContentBlock
        | ImageGalleryBlock
        | FeaturesListBlock
        | SpecificationsBlock
        | CallToActionBlock
        | TestimonialsBlock
      )[]
    | null;
  /**
   * Detailed product specifications and data
   */
  productData?: {
    /**
     * Product model number
     */
    model?: string | null;
    /**
     * Product brand
     */
    brand?: string | null;
    /**
     * Product series/collection
     */
    series?: string | null;
    /**
     * Stock Keeping Unit (SKU)
     */
    sku?: string | null;
    /**
     * Product weight (e.g., "68kg", "150 lbs")
     */
    weight?: string | null;
    dimensions?: {
      /**
       * Width (e.g., "145cm", "57 inches")
       */
      width?: string | null;
      /**
       * Depth (e.g., "46cm", "18 inches")
       */
      depth?: string | null;
      /**
       * Height (e.g., "88cm", "35 inches")
       */
      height?: string | null;
    };
    /**
     * Warranty information
     */
    warranty?: string | null;
    /**
     * Country of manufacture
     */
    origin?: string | null;
  };
  /**
   * SEO and social media optimization
   */
  seo?: {
    /**
     * Custom meta title (defaults to product title)
     */
    metaTitle?: string | null;
    /**
     * Meta description for search engines (max 160 characters)
     */
    metaDescription?: string | null;
    /**
     * SEO keywords (comma-separated)
     */
    keywords?: string | null;
    /**
     * Open Graph image for social sharing (defaults to main image)
     */
    ogImage?: (string | null) | Media;
  };
  /**
   * Product visibility and display settings
   */
  visibility?: {
    /**
     * Feature this product prominently
     */
    featured?: boolean | null;
    /**
     * Show in product catalog/listings
     */
    showInCatalog?: boolean | null;
    /**
     * Allow customer reviews for this product
     */
    allowReviews?: boolean | null;
    /**
     * Sort order (lower numbers appear first)
     */
    sortOrder?: number | null;
  };
  /**
   * Inventory management settings
   */
  inventory?: {
    /**
     * Track inventory for this product
     */
    trackStock?: boolean | null;
    /**
     * Current stock quantity
     */
    stockQuantity?: number | null;
    /**
     * Alert when stock falls below this number
     */
    lowStockThreshold?: number | null;
    /**
     * Product is currently in stock
     */
    inStock?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  /**
   * Choose data source for hero content
   */
  dataSource?: ('manual' | 'pianomodel' | 'hybrid') | null;
  /**
   * Select piano model to automatically populate hero content
   */
  pianoModel?: (string | null) | PianoModel;
  /**
   * Hero content and call-to-action buttons
   */
  content?: {
    /**
     * Main hero title/headline (leave empty to use Piano Model name)
     */
    title?: string | null;
    /**
     * Optional subtitle or tagline (leave empty to use Piano Model short description)
     */
    subtitle?: string | null;
    /**
     * Hero description text (leave empty to use Piano Model description)
     */
    description?: string | null;
    /**
     * Primary call-to-action button
     */
    primaryCta?: {
      /**
       * Primary button text (leave empty to hide button)
       */
      text?: string | null;
      /**
       * Primary button link/URL
       */
      link?: string | null;
      style?: ('primary' | 'secondary' | 'outline') | null;
      openInNewTab?: boolean | null;
    };
    /**
     * Secondary call-to-action button (optional)
     */
    secondaryCta?: {
      /**
       * Secondary button text (leave empty to hide button)
       */
      text?: string | null;
      /**
       * Secondary button link/URL
       */
      link?: string | null;
      style?: ('primary' | 'secondary' | 'outline') | null;
      openInNewTab?: boolean | null;
    };
  };
  /**
   * Background media and overlay settings
   */
  media?: {
    /**
     * Type of background media
     */
    type?: ('image' | 'video' | 'none') | null;
    /**
     * Background image (leave empty to use Piano Model main image)
     */
    backgroundImage?: (string | null) | Media;
    /**
     * Background video
     */
    backgroundVideo?: (string | null) | Media;
    /**
     * Background overlay settings
     */
    overlay?: {
      /**
       * Add overlay to improve text readability
       */
      enable?: boolean | null;
      color?: ('dark' | 'light' | 'brand') | null;
      /**
       * Overlay opacity (0 = transparent, 1 = opaque)
       */
      opacity?: number | null;
    };
  };
  /**
   * Layout and positioning options
   */
  layout?: {
    /**
     * Hero section height
     */
    height?: ('small' | 'medium' | 'large' | 'fullscreen') | null;
    /**
     * Text content alignment
     */
    contentAlignment?: ('left' | 'center' | 'right') | null;
    /**
     * Vertical content alignment
     */
    verticalAlignment?: ('top' | 'center' | 'bottom') | null;
    /**
     * Maximum width of content area
     */
    maxWidth?: ('small' | 'medium' | 'large' | 'full') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextContentBlock".
 */
export interface TextContentBlock {
  /**
   * Rich text content with full formatting capabilities
   */
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Layout and styling options
   */
  layout?: {
    /**
     * Maximum width of text content
     */
    maxWidth?: ('small' | 'medium' | 'large' | 'full') | null;
    /**
     * Text alignment
     */
    textAlign?: ('left' | 'center' | 'right' | 'justify') | null;
    /**
     * Background color for the content area
     */
    backgroundColor?: ('none' | 'light-gray' | 'dark-gray' | 'brand' | 'accent') | null;
    /**
     * Padding around the content
     */
    padding?: ('none' | 'small' | 'medium' | 'large') | null;
    /**
     * Number of columns for text layout
     */
    columns?: ('one' | 'two' | 'three') | null;
  };
  /**
   * Enable drop cap (large first letter) for the first paragraph
   */
  enableDropCap?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'textContent';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageGalleryBlock".
 */
export interface ImageGalleryBlock {
  /**
   * Choose data source for gallery images
   */
  dataSource?: ('manual' | 'pianomodel' | 'hybrid') | null;
  /**
   * Select piano model to automatically populate gallery from model images
   */
  pianoModel?: (string | null) | PianoModel;
  /**
   * Optional gallery title
   */
  title?: string | null;
  /**
   * Optional gallery description
   */
  description?: string | null;
  /**
   * Images to display in the gallery (additional images when using Piano Model data source)
   */
  images?:
    | {
        /**
         * Gallery image
         */
        image: string | Media;
        /**
         * Image caption (optional)
         */
        caption?: string | null;
        /**
         * Alt text for accessibility (optional, will use image alt if not provided)
         */
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Gallery layout and display options
   */
  layout?: {
    /**
     * Gallery display style
     */
    style?: ('grid' | 'masonry' | 'carousel' | 'lightbox') | null;
    /**
     * Number of columns for grid layouts
     */
    columns?: ('two' | 'three' | 'four' | 'five') | null;
    /**
     * Spacing between images
     */
    spacing?: ('none' | 'small' | 'medium' | 'large') | null;
    /**
     * Aspect ratio for images in grid layouts
     */
    aspectRatio?: ('original' | 'square' | 'landscape' | 'portrait') | null;
  };
  /**
   * Carousel-specific settings
   */
  carouselSettings?: {
    /**
     * Auto-advance slides
     */
    autoplay?: boolean | null;
    /**
     * Autoplay speed in milliseconds
     */
    autoplaySpeed?: number | null;
    /**
     * Show navigation dots
     */
    showDots?: boolean | null;
    /**
     * Show navigation arrows
     */
    showArrows?: boolean | null;
    /**
     * Number of slides to show at once
     */
    slidesToShow?: ('one' | 'two' | 'three' | 'four') | null;
    /**
     * Enable infinite loop
     */
    infinite?: boolean | null;
  };
  /**
   * Enable image zoom on hover/click
   */
  enableZoom?: boolean | null;
  /**
   * Display image captions
   */
  showCaptions?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'imageGallery';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturesListBlock".
 */
export interface FeaturesListBlock {
  /**
   * Choose data source for features list
   */
  dataSource?: ('manual' | 'pianomodel' | 'hybrid') | null;
  /**
   * Select piano model to automatically populate key features
   */
  pianoModel?: (string | null) | PianoModel;
  /**
   * Optional header content for the features section
   */
  header?: {
    /**
     * Section title (optional)
     */
    title?: string | null;
    /**
     * Section subtitle (optional)
     */
    subtitle?: string | null;
    /**
     * Section description (optional)
     */
    description?: string | null;
  };
  /**
   * List of features to display
   */
  features: {
    /**
     * Icon configuration for this feature
     */
    icon?: {
      /**
       * Type of icon to display
       */
      type?: ('none' | 'image' | 'icon' | 'emoji') | null;
      /**
       * Custom icon image
       */
      image?: (string | null) | Media;
      /**
       * Icon name (e.g., "check", "star", "music")
       */
      iconName?: string | null;
      /**
       * Emoji character (e.g., "🎹", "✨", "🎵")
       */
      emoji?: string | null;
    };
    /**
     * Feature title/name
     */
    title: string;
    /**
     * Feature description (optional)
     */
    description?: string | null;
    /**
     * Highlight this feature with special styling
     */
    highlight?: boolean | null;
    id?: string | null;
  }[];
  /**
   * Layout and styling options
   */
  layout?: {
    /**
     * Display style for features
     */
    style?: ('grid' | 'list' | 'cards' | 'minimal') | null;
    /**
     * Number of columns for grid/cards layouts
     */
    columns?: ('one' | 'two' | 'three' | 'four') | null;
    /**
     * Position of icons relative to text
     */
    iconPosition?: ('left' | 'top' | 'right') | null;
    /**
     * Spacing between features
     */
    spacing?: ('compact' | 'medium' | 'spacious') | null;
    /**
     * Background color for the features section
     */
    backgroundColor?: ('none' | 'light-gray' | 'dark-gray' | 'brand' | 'accent') | null;
  };
  /**
   * Show numbered list (1, 2, 3...) instead of icons
   */
  showNumbers?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featuresList';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SpecificationsBlock".
 */
export interface SpecificationsBlock {
  /**
   * Choose data source for specifications
   */
  dataSource?: ('manual' | 'pianomodel' | 'hybrid') | null;
  /**
   * Select piano model to automatically populate specifications
   */
  pianoModel?: (string | null) | PianoModel;
  /**
   * Header content for the specifications section
   */
  header?: {
    /**
     * Section title
     */
    title?: string | null;
    /**
     * Optional description above specifications
     */
    description?: string | null;
  };
  /**
   * Additional specification categories (leave empty to use Piano Model specifications only)
   */
  categories?:
    | {
        /**
         * Category name (e.g., "Dimensions", "Sound", "Features")
         */
        categoryName: string;
        /**
         * Individual specifications within this category
         */
        specifications: {
          /**
           * Specification label (e.g., "Width", "Polyphony", "Weight")
           */
          label: string;
          /**
           * Specification value (e.g., "145cm", "256 notes", "68kg")
           */
          value: string;
          /**
           * Highlight this specification as important
           */
          highlight?: boolean | null;
          /**
           * Additional note or context (optional)
           */
          note?: string | null;
          id?: string | null;
        }[];
        /**
         * Make this category collapsible/expandable
         */
        collapsible?: boolean | null;
        /**
         * Start expanded (only applies if collapsible is enabled)
         */
        defaultExpanded?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Layout and styling options
   */
  layout?: {
    /**
     * Display style for specifications
     */
    style?: ('table' | 'cards' | 'list' | 'grid') | null;
    /**
     * Number of columns for categories
     */
    columns?: ('one' | 'two' | 'three') | null;
    /**
     * Show icons next to category names
     */
    showCategoryIcons?: boolean | null;
    /**
     * Alternate row colors for better readability
     */
    alternateRows?: boolean | null;
    /**
     * Use compact spacing for dense information display
     */
    compactMode?: boolean | null;
  };
  /**
   * Options for downloading detailed specifications
   */
  downloadOptions?: {
    /**
     * Allow users to download specifications as PDF/document
     */
    enableDownload?: boolean | null;
    /**
     * Specifications document to download
     */
    downloadFile?: (string | null) | Media;
    /**
     * Download button text
     */
    downloadButtonText?: string | null;
  };
  /**
   * Enable comparison view (useful for product comparison pages)
   */
  comparisonMode?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'specifications';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  /**
   * Main content for the call-to-action
   */
  content: {
    /**
     * Main CTA title/headline
     */
    title: string;
    /**
     * Optional subtitle or supporting text
     */
    subtitle?: string | null;
    /**
     * CTA description or value proposition
     */
    description?: string | null;
  };
  /**
   * Action buttons for the CTA
   */
  buttons: {
    /**
     * Button text
     */
    text: string;
    /**
     * Button link/URL
     */
    link: string;
    /**
     * Button visual style
     */
    style?: ('primary' | 'secondary' | 'outline' | 'ghost' | 'link') | null;
    /**
     * Button size
     */
    size?: ('small' | 'medium' | 'large') | null;
    /**
     * Optional icon name (e.g., "arrow-right", "download", "phone")
     */
    icon?: string | null;
    /**
     * Icon position relative to text
     */
    iconPosition?: ('left' | 'right') | null;
    /**
     * Open link in new tab
     */
    openInNewTab?: boolean | null;
    id?: string | null;
  }[];
  /**
   * Media and visual elements
   */
  media?: {
    /**
     * Type of media to include
     */
    type?: ('none' | 'background' | 'side' | 'icon') | null;
    /**
     * Background image for the CTA section
     */
    backgroundImage?: (string | null) | Media;
    /**
     * Side image to display alongside content
     */
    sideImage?: (string | null) | Media;
    /**
     * Icon name (e.g., "star", "heart", "trophy")
     */
    iconName?: string | null;
    /**
     * Position of side image relative to content
     */
    imagePosition?: ('left' | 'right') | null;
    /**
     * Background overlay settings
     */
    overlay?: {
      /**
       * Add overlay to improve text readability
       */
      enable?: boolean | null;
      color?: ('dark' | 'light' | 'brand') | null;
      /**
       * Overlay opacity
       */
      opacity?: number | null;
    };
  };
  /**
   * Layout and styling options
   */
  layout?: {
    /**
     * Overall CTA design style
     */
    style?: ('banner' | 'card' | 'minimal' | 'split') | null;
    /**
     * Content alignment
     */
    alignment?: ('left' | 'center' | 'right') | null;
    /**
     * CTA section size/padding
     */
    size?: ('small' | 'medium' | 'large') | null;
    /**
     * Background color for the CTA section
     */
    backgroundColor?: ('none' | 'light-gray' | 'dark-gray' | 'brand' | 'accent' | 'gradient') | null;
    /**
     * Button arrangement when multiple buttons are present
     */
    buttonLayout?: ('horizontal' | 'vertical') | null;
  };
  /**
   * Urgency and scarcity elements
   */
  urgency?: {
    /**
     * Add urgency elements (countdown, limited time, etc.)
     */
    enableUrgency?: boolean | null;
    /**
     * Urgency message (e.g., "Limited time offer", "Only 3 left in stock")
     */
    urgencyText?: string | null;
    /**
     * Show countdown timer
     */
    showCountdown?: boolean | null;
    /**
     * Countdown end date and time
     */
    countdownEndDate?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'callToAction';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock".
 */
export interface TestimonialsBlock {
  /**
   * Header content for the testimonials section
   */
  header?: {
    /**
     * Section title
     */
    title?: string | null;
    /**
     * Optional subtitle
     */
    subtitle?: string | null;
    /**
     * Optional description above testimonials
     */
    description?: string | null;
  };
  /**
   * Customer testimonials and reviews
   */
  testimonials: {
    /**
     * Customer testimonial/review text
     */
    quote: string;
    /**
     * Star rating (1-5 stars, optional)
     */
    rating?: number | null;
    /**
     * Customer information
     */
    customer: {
      /**
       * Customer name
       */
      name: string;
      /**
       * Customer title/position (optional)
       */
      title?: string | null;
      /**
       * Customer company/organization (optional)
       */
      company?: string | null;
      /**
       * Customer location (optional)
       */
      location?: string | null;
      /**
       * Customer photo/avatar (optional)
       */
      avatar?: (string | null) | Media;
    };
    /**
     * Product being reviewed (optional)
     */
    product?: string | null;
    /**
     * Mark as verified purchase/review
     */
    verified?: boolean | null;
    /**
     * Feature this testimonial prominently
     */
    featured?: boolean | null;
    /**
     * Source of the review (optional)
     */
    source?: ('direct' | 'google' | 'facebook' | 'trustpilot' | 'yelp' | 'amazon' | 'other') | null;
    /**
     * Date of review (optional)
     */
    reviewDate?: string | null;
    id?: string | null;
  }[];
  /**
   * Layout and display options
   */
  layout?: {
    /**
     * Display style for testimonials
     */
    style?: ('cards' | 'carousel' | 'grid' | 'list' | 'masonry') | null;
    /**
     * Number of columns for grid/card layouts
     */
    columns?: ('one' | 'two' | 'three' | 'four') | null;
    /**
     * Display customer avatars/photos
     */
    showAvatars?: boolean | null;
    /**
     * Display star ratings
     */
    showRatings?: boolean | null;
    /**
     * Show review source (Google, Facebook, etc.)
     */
    showSource?: boolean | null;
    /**
     * Show review dates
     */
    showDates?: boolean | null;
    /**
     * Background color for the testimonials section
     */
    backgroundColor?: ('none' | 'light-gray' | 'dark-gray' | 'brand' | 'white') | null;
  };
  /**
   * Carousel-specific settings
   */
  carouselSettings?: {
    /**
     * Auto-advance testimonials
     */
    autoplay?: boolean | null;
    /**
     * Autoplay speed in milliseconds
     */
    autoplaySpeed?: number | null;
    /**
     * Show navigation dots
     */
    showDots?: boolean | null;
    /**
     * Show navigation arrows
     */
    showArrows?: boolean | null;
    /**
     * Number of testimonials to show at once
     */
    slidesToShow?: ('one' | 'two' | 'three') | null;
    /**
     * Enable infinite loop
     */
    infinite?: boolean | null;
  };
  /**
   * Overall rating and review summary
   */
  aggregateRating?: {
    /**
     * Show overall rating summary
     */
    showOverallRating?: boolean | null;
    /**
     * Overall rating score
     */
    overallRating?: number | null;
    /**
     * Total number of reviews
     */
    totalReviews?: number | null;
    /**
     * Rating description (e.g., "Excellent", "Based on 150 reviews")
     */
    ratingText?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonials';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * Manage all content for the main Pianos page including hero, categories, featured models, and CTAs.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pianos-page".
 */
export interface PianosPage {
  id: string;
  /**
   * Main page title displayed in the hero section
   */
  heroTitle: string;
  /**
   * Hero description text displayed below the title
   */
  heroDescription: string;
  /**
   * Background image for the hero section
   */
  heroBackgroundImage?: (string | null) | Media;
  /**
   * Hero call-to-action button configuration
   */
  heroCta: {
    /**
     * Call-to-action button text
     */
    text: string;
    /**
     * Call-to-action button link/URL
     */
    link: string;
  };
  /**
   * The four main piano categories displayed on the page
   */
  pianoCategories: {
    /**
     * URL slug for this category (e.g., "grand", "digital")
     */
    slug: string;
    /**
     * Category display name (e.g., "Acoustic Grand Pianos")
     */
    name: string;
    /**
     * Category description text
     */
    description: string;
    /**
     * Category representative image
     */
    image?: (string | null) | Media;
    /**
     * Price range for this category (e.g., "$45,000 - $185,000")
     */
    priceRange?: string | null;
    /**
     * Key features of this piano category
     */
    features?:
      | {
          feature: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Icon to display for this category
     */
    icon?: ('piano' | 'music' | 'zap' | 'award' | 'crown') | null;
    /**
     * Badge text (e.g., "Professional", "Classic")
     */
    badge?: string | null;
    /**
     * Highlighted feature or series (e.g., "GX BLAK Performance Series")
     */
    highlight?: string | null;
    id?: string | null;
  }[];
  /**
   * Featured models section header content
   */
  featuredModelsSection: {
    /**
     * Section title for featured models
     */
    title: string;
    /**
     * Section description for featured models
     */
    description: string;
  };
  /**
   * Three featured piano models for the carousel
   */
  featuredModels: {
    /**
     * Piano model name (e.g., "GX-7 BLAK")
     */
    name: string;
    /**
     * Piano category/series (e.g., "GX BLAK Performance Series")
     */
    category: string;
    /**
     * Featured model image for carousel
     */
    image?: (string | null) | Media;
    /**
     * Badge text (e.g., "Performance Series", "Flagship Digital")
     */
    badge?: string | null;
    /**
     * Model description for carousel slide
     */
    description: string;
    id?: string | null;
  }[];
  /**
   * Final call-to-action section configuration
   */
  ctaSection: {
    /**
     * CTA section main title
     */
    title: string;
    /**
     * CTA section description text
     */
    description: string;
    /**
     * Call-to-action button text
     */
    ctaText: string;
    /**
     * Call-to-action button link/URL
     */
    ctaLink: string;
  };
  /**
   * SEO and metadata configuration
   */
  seo?: {
    /**
     * Page meta title for search engines
     */
    metaTitle?: string | null;
    /**
     * Page meta description for search engines (max 160 characters)
     */
    metaDescription?: string | null;
    /**
     * SEO keywords (comma-separated)
     */
    keywords?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'productlines';
        value: string | Productline;
      } | null)
    | ({
        relationTo: 'piano-models';
        value: string | PianoModel;
      } | null)
    | ({
        relationTo: 'pianos-page';
        value: string | PianosPage;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  description?: T;
  mediaType?: T;
  usage?: T;
  videoMeta?:
    | T
    | {
        duration?: T;
        thumbnail?: T;
        autoplay?: T;
        muted?: T;
      };
  variants?:
    | T
    | {
        mobile?: T;
        tablet?: T;
        desktop?: T;
        largeDesktop?: T;
      };
  seoMeta?:
    | T
    | {
        focusKeywords?: T;
        photographerCredit?: T;
        copyrightInfo?: T;
        originalSource?: T;
      };
  featured?: T;
  tags?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        desktop?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productlines_select".
 */
export interface ProductlinesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  category?: T;
  description?: T;
  highlight?: T;
  image?: T;
  slides?:
    | T
    | {
        title?: T;
        image?: T;
        id?: T;
      };
  pianoModels?: T;
  featured?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "piano-models_select".
 */
export interface PianoModelsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  model?: T;
  productline?: T;
  description?: T;
  shortDescription?: T;
  image?: T;
  keyFeatures?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  specifications?:
    | T
    | {
        keys?: T;
        pedals?: T;
        voices?: T;
        polyphony?: T;
        dimensions?:
          | T
          | {
              width?: T;
              depth?: T;
              height?: T;
            };
        weight?: T;
        actionType?: T;
        soundEngine?: T;
      };
  availableFinishes?:
    | T
    | {
        name?: T;
        image?: T;
        priceModifier?: T;
        available?: T;
        description?: T;
        id?: T;
      };
  pricing?:
    | T
    | {
        currency?: T;
        msrp?: T;
        salePrice?: T;
        priceRange?: T;
        priceText?: T;
        contactForPricing?: T;
        showPrice?: T;
      };
  product?: T;
  autoGenerateProduct?: T;
  status?: T;
  featured?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pianos-page_select".
 */
export interface PianosPageSelect<T extends boolean = true> {
  heroTitle?: T;
  heroDescription?: T;
  heroBackgroundImage?: T;
  heroCta?:
    | T
    | {
        text?: T;
        link?: T;
      };
  pianoCategories?:
    | T
    | {
        slug?: T;
        name?: T;
        description?: T;
        image?: T;
        priceRange?: T;
        features?:
          | T
          | {
              feature?: T;
              id?: T;
            };
        icon?: T;
        badge?: T;
        highlight?: T;
        id?: T;
      };
  featuredModelsSection?:
    | T
    | {
        title?: T;
        description?: T;
      };
  featuredModels?:
    | T
    | {
        name?: T;
        category?: T;
        image?: T;
        badge?: T;
        description?: T;
        id?: T;
      };
  ctaSection?:
    | T
    | {
        title?: T;
        description?: T;
        ctaText?: T;
        ctaLink?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  type?: T;
  pianoModel?: T;
  dataSource?: T;
  name?: T;
  slug?: T;
  category?: T;
  status?: T;
  mainImage?: T;
  title?: T;
  description?: T;
  price?:
    | T
    | {
        currency?: T;
        amount?: T;
        saleAmount?: T;
        priceText?: T;
        showPrice?: T;
      };
  finishes?:
    | T
    | {
        name?: T;
        image?: T;
        priceModifier?: T;
        available?: T;
        id?: T;
      };
  buyButton?:
    | T
    | {
        text?: T;
        link?: T;
        style?: T;
        showButton?: T;
      };
  pageContent?: T | {};
  productData?:
    | T
    | {
        model?: T;
        brand?: T;
        series?: T;
        sku?: T;
        weight?: T;
        dimensions?:
          | T
          | {
              width?: T;
              depth?: T;
              height?: T;
            };
        warranty?: T;
        origin?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        ogImage?: T;
      };
  visibility?:
    | T
    | {
        featured?: T;
        showInCatalog?: T;
        allowReviews?: T;
        sortOrder?: T;
      };
  inventory?:
    | T
    | {
        trackStock?: T;
        stockQuantity?: T;
        lowStockThreshold?: T;
        inStock?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}